export default [
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "magic wand",
        image: require("image/items/Magic_Wand_icon.png"),
        price: "400",
        add_stats: [
            {
                value: "+2 ",
                feature: "ко всем атрибутам",
            },
            {
                value: "+1.5 ",
                feature: "к регенерации здоровья",
            }
        ],
        usage: "energy charge",
        description: "Мгновенно восстанавливает 15 здоровья и маны за каждый имеющийся заряд. Может иметь до 17 зарядов. Получает один заряд, когда видимый враг в радиусе 1200 использует способность.",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "ring of basilius",
        image: require("image/items/Ring_of_Basilius_(Inactive)_icon.png"),
        price: "500",
        add_stats: [{
            value: "+7 ",
            feature: "к урону",
        }],
        usage: "basilius aura",
        description: "Пассивная: Увеличивает восстановление маны на 0.5 и броню на 2 в радиусе 900; Активная: Если выключить способность, аура будет действовать только на героев",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "glimmer cape",
        image: require("image/items/Glimmer_Cape_icon.png"),
        price: "1850",
        add_stats: [
            {
                value: "+20 ",
                feature: "к скорости атаки",
            },
            {
                value: "+15% ",
                feature: "к сопротивлению магии",
            },
        ],
        usage: "Glimmer",
        description: "Активируемая: ",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "hood of defiance",
        image: require("image/items/Hood_of_Defiance_icon.png"),
        price: "1700",
        add_stats: [
            {
                value: "+6.5 ",
                feature: "к регенерации здоровья",
            },
            {
                value: "+25% ",
                feature: "к сопротивлению магии",
            },
        ],
        usage: "Barrier",
        description: "Создает щит, блокирующий до 325 магического урона",
        notation: "Действует 12 сек.",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "crystalys",
        image: require("image/items/Crystalys_icon.png"),
        price: "2120",
        add_stats: [{
            value: "+30 ",
            feature: "к урону",
        }],
        usage: "Critical Strike",
        description: "Каждая атака может с вероятностью в 20% нанести 175% урона",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "dragon lance",
        image: require("image/items/Dragon_Lance_icon.png"),
        price: "1900",
        add_stats: [
            {
                value: "+12 ",
                feature: "к ловкости",
            },
            {
                value: "+12 ",
                feature: "к силе",
            },
        ],
        usage: "Dragon's Reach",
        description: "Увеличивает дальность атаки героев дальнего боя на 140",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "null talisman",
        image: require("image/items/Null_Talisman_icon.png"),
        price: "465",
        add_stats: [
            {
                value: "+3 ",
                feature: "к силе",
            },
            {
                value: "+3 ",
                feature: "к ловкости",
            },
            {
                value: "+7",
                feature: "к интеллекту",
            },
        ],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "headdress",
        image: require("image/items/Headdress_icon.png"),
        price: "650",
        add_stats: [{
            value: "+2 ",
            feature: "ко всем атрибутам",
        }],
        usage: "Regeneration Aura",
        description: "Увеличивает восстановление здоровья союзников на 2",
        notation: "Радиус: 900",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "veil of discord",
        image: require("image/items/Veil_of_Discord_icon.png"),
        price: "2330",
        add_stats: [
            {
                value: "+5 ",
                feature: "к регенерации здоровья",
            },
            {
                value: "+6 ",
                feature: "к броне",
            },
            {
                value: "+6 ",
                feature: "к ловкости",
            },
            {
                value: "+6 ",
                feature: "к силе",
            },
            {
                value: "+14 ",
                feature: "к интеллекту",
            },
        ],
        usage: "Magic Weakness",
        description: "Ослабляет врагов в радиусе 600, уменьшая их магическое сопротивления на 25%",
        notation: "Дальности приминения: 1000, Длительность: 16 сек.",
    },
    {
        base_shop: false,
        secretShop: false,
        sideShop: false,
        title: "vanguard",
        image: require("image/items/Vanguard_icon.png"),
        price: "2150",
        add_stats: [
            {
                value: "+250 ",
                feature: "к здоровью",
            },
            {
                value: "+5.5 ",
                feature: "к регенерации здоровья",
            },
        ],
        usage: "Damage Block",
        description: "С вероятностью в 50% блокирует 70 урона от атак, если владелец - герой ближнего боя, или 35 урона, если герой дальнего боя",
        notation: "Эффекты нескольких способностей, блокирующих урон, не сочетаются",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "armlet of mordiggian",
        image: require("image/items/Armlet_of_Mordiggian_(Inactive)_icon.png"),
        price: "2370",
        add_stats: [
            {
                value: "+9 ",
                feature: "к урону",
            },
            {
                value: "+25 ",
                feature: "к скорости атаки",
            },
            {
                value: "+5 ",
                feature: "к броне",
            },
            {
                value: "+4 ",
                feature: "к регенерации здоровья",
            },
        ],
        usage: "Unholy Strength",
        description: "Если включена увеличивает урон на 31, силу на 25 и защиту на 4, но отнимает 54 здоровья в секунду. Вы не можете умереть ни от потери здоровья из-за способности, ни от спада бонуса к силе после ее отключения",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "sange",
        image: require("image/items/Sange_icon.png"),
        price: "1950",
        add_stats: [
            {
                value: "+10 ",
                feature: "к урону",
            },
            {
                value: "+16 ",
                feature: "к силе",
            },
        ],
        usage: "Lesser Maim", 
        description: "Каждая атака с вероятностью 30% может нанести травму, замедляющую врага в зависимости от атаки владельца. Длительность травмы: 5.",
        notation: "Замедление(ближний бой): передвижение 20%, атака 20. Замедление(дальний бой): передвижеие 10%, атака 10",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "wraith band",
        image: require("image/items/Wraith_Band_icon.png"),
        price: "465",
        add_stats: [
            {
                value: "+3 ",
                feature: "к силе",
            },
            {
                value: "+7 ",
                feature: "к ловкости",
            },
            {
                value: "+3 ",
                feature: "к интеллекту",
            },
        ],
        usage: "", 
        description: "",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "buckler",
        image: require("image/items/Buckler_icon.png"),
        price: "800",
        add_stats: [
            {
                value: "+5 ",
                feature: "к броне",
            },
            {
                value: "+2 ",
                feature: "ко всем атрибутам",
            },
        ],
        usage: "Armor Bonus", 
        description: "Дает союзным существам 2 брони. Действует 25 секунд на героев и 30 секунд на прочих существ.",
        notation: "Радиус: 900",
    },
    {
        base_shop: false,
        secretShop: false,
        sideShop: false,
        title: "aether lens",
        image: require("image/items/Aether_Lens_icon.png"),
        price: "2360",
        add_stats: [
            {
                value: "+450 ",
                feature: "к мане",
            },
            {
                value: "+1.25 ",
                feature: "к восстановлению маны",
            },
        ],
        usage: "Aethereal Focus", 
        description: "Увеличивает дальность приминения способностей и предметов на 250",
        notation: "Эффекты от пассивной способности не складываются",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: true,
        title: "blade mail",
        image: require("image/items/Blade_Mail_icon.png"),
        price: "2200",
        add_stats: [
            {
                value: "+22 ",
                feature: "к урону",
            },
            {
                value: "+6 ",
                feature: "к броне",
            },
            {
                value: "+10 ",
                feature: "к интеллекту",
            },
        ],
        usage: "Damaged Returned", 
        description: "Отражает любой получаемый урон наносящему его врагу. Длится 4.5 сек.",
        notation: "Урон возвращается в изначальном количестве, до его уменьшения. Не отражает урон от других Blade Mail и схожих способностей. Возвращаемый урон имеет тот же тип, что и полученный. Если нанесенный урон проходит сквозь невосприимчивость к магии, то проходит и отраженный.",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "meteor hammer",
        image: require("image/items/Meteor_Hammer_icon.png"),
        price: "2625",
        add_stats: [
            {
                value: "+12 ",
                feature: "к силе",
            },
            {
                value: "12 ",
                feature: "+к интеллекту",
            },
            {
                value: "+4 ",
                feature: "к регенерации здоровья",
            },
            {
                value: "+1.5 ",
                feature: "к восстановлению маны",
            },
        ],
        usage: "Meteor Hammer", 
        description: "ПРЕРЫВАЕМАЯ - призывает метеорит, который после небольшой задержки бьет по области радиусом 300. Удар наносит урон вражеским существам и постройкам, оглушает их на 2 сек. и поджигает, нанося периодический урон в течении 6 сек.",
        notation: "Урон постройкам при ударе 75, периодический урон постройкам 50, урон существам при ударе 150, периодический урон 90. Время приминения 2.5 сек, задержка после приминения 0.5 сек",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "yasha",
        image: require("image/items/Yasha_icon.png"),
        price: "1950",
        add_stats: [
            {
                value: "+16 ",
                feature: "к ловкости",
            },
            {
                value: "10 ",
                feature: "к скорости атаки",
            },
            {
                value: "+8% ",
                feature: "к скорости передвижения",
            },
        ],
        usage: "", 
        description: "",
        notation: "Бонусы к скорости от нескольких предметов на основе Yasha не склыдваются",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "bracer",
        image: require("image/items/Bracer_icon.png"),
        price: "465",
        add_stats: [
            {
                value: "+7 ",
                feature: "к силе",
            },
            {
                value: "+3 ",
                feature: "к ловкости",
            },
            {
                value: "+3 ",
                feature: "+к интеллекту",
            },
        ],
        usage: "", 
        description: "",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "urn of shadows",
        image: require("image/items/Urn_of_Shadows_icon.png"),
        price: "875",
        add_stats: [
            {
                value: "+1 ",
                feature: "к восстановлению маны",
            },
            {
                value: "+2 ",
                feature: "ко всем атрибутам",
            },
            {
                value: "+2 ",
                feature: "к броне",
            },
        ],
        usage: "Soul Release", 
        description: "Эффект зависит от выбранной цели: либо увеличивает восстановление здоровья союзника на 35, либо наносит противнику 25 урону в секунду. Действует 8 сек. Получает заряды каждый раз, когда в радиусе 1400 умирает вражеский герой. Заряд получит только один, ближайший к умершему герою предмет. Дальность приминения: 950",
        notation: "Пустая урна получает 2 заряда. Если применить на противника, на котрого уже действует этот предмет, длительность предмета обновится. Эффект можно развеять.",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "force staff",
        image: require("image/items/Force_Staff_icon.png"),
        price: "2250",
        add_stats: [
            {
                value: "+10 ",
                feature: "к интеллекту",
            },
            {
                value: "+5 ",
                feature: "к регенерации здоровья",
            },
        ],
        usage: "Force", 
        description: "Толакает выбранное существо в направление его взгляда на расстояние в 600. Дальность приминения: 750",
        notation: "Можно применить на себя. Не прерывает действие цели. Не работает на существ под воздействием способностей Chronosphere, Duel или Black Hole",
    },
    {
        base_shop: true,
        secretShop: true,
        sideShop: false,
        title: "soul booster",
        image: require("image/items/Soul_Booster_icon.png"),
        price: "3200",
        add_stats: [
            {
                value: "+425 ",
                feature: "к здоровью",
            },
            {
                value: "+425 ",
                feature: "к мане",
            },
        ],
        usage: "", 
        description: "",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "shadow blade",
        image: require("image/items/Shadow_Blade_icon.png"),
        price: "2700",
        add_stats: [
            {
                value: "+22 ",
                feature: "к урону",
            },
            {
                value: "+30 ",
                feature: "к скорости атаки",
            },
        ],
        usage: "Shadow Walk", 
        description: "Делает героя невидимым на 14 сек. или до момента, когда совершит атаку или применит способность. Также увеличивает скорость передвижения на 20% и позволяет проходить сквозь существ. Атака прерывающая невидимость, дополнительно нанесет 175 физического урона",
        notation: "Задержка перед невидимостью - 0.3 секунды. Если невидимость закончится без атаки, дополнительный урон будет потерян",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "kaya",
        image: require("image/items/Kaya_icon.png"),
        price: "1950",
        add_stats: [
            {
                value: "+16 ",
                feature: "к интеллекту"
            },
            {
                value: "+10% ",
                feature: "к урону от способностей",
            },
        ],
        usage: "", 
        description: "Уменьшение расхода и потери маны 10%",
        notation: "Эффекты от нескольких таких предметов не складываются",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "soul ring",
        image: require("image/items/Soul_Ring_icon.png"),
        price: "770",
        add_stats: [
            {
                value: "+6 ",
                feature: "к силе",
            },
            {
                value: "+2 ",
                feature: "к регенерации здоровья",
            },
        ],
        usage: "Sacrifice", 
        description: "Отнимает 150 здоровья, временно пополняя запас маны на 150. Действует 10 сек. Герой получит дополнительную ману, даже если она не умещается в ее максимальный запас",
        notation: "Если полученную ману не использовать за время действия предмета, она исчезнет",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "tranquil boots",
        image: require("image/items/Tranquil_Boots_(Active)_icon.png"),
        price: "950",
        add_stats: [
            {
                value: "+90 ",
                feature: "к скорости передвижения",
            },
            {
                value: "+13 ",
                feature: "к регенерации здоровья",
            },
        ],
        usage: "Break", 
        description: "Если владельца атаковали или он атаковал сам, то предмет 13 сек. будет восстанавливать на 13 здоровья в секунду меньше, а бонус к скорости передвижения уменьшится на 65",
        notation: "Основные бонусы к скорости передвижения от нескольких пар ботинок не складываются",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "necronomicon",
        image: require("image/items/Necronomicon_1_icon.png"),
        price: "2400",
        add_stats: [
            {
                value: "+10/15/20 ",
                feature: "к силе",
            },
            {
                value: "1/1.25/1.5 ",
                feature: "к восстановлению маны",
            },
        ],
        usage: "Summoning", 
        description: "Призывает на 50 сек. подконтрольных вам воина и лучника. ВОИН: каждой атакой сжигает ману цели и наносит магический урон тому, кто его убьет. На третьем уровне получает эффект True Sight, раскрывающий невидимость. ЛУЧНИК: имеет ауру, увеличивающая скорость атаки и передвижения союзников. На третьем уровне получает способность, развеивающую положительные эффекты противника",
        notation: "ВОИН: здоровье 700/800/900, урон 75/100/125, сжигание маны 30/40/50, урон при смерти 550/675/800; ЛУЧНИК: здоровье 700/800/900, урон 60/90/120, доп. скорость передвижения 5/7/9, доп. скорость атаки 5/7/9, радиус ауры 900",
    },
    {
        base_shop: false,
        secretShop: false,
        sideShop: false,
        title: "crimson guard",
        image: require("image/items/Crimson_Guard_icon.png"),
        price: "3550",
        add_stats: [
            {
                value: "+250 ",
                feature: "к здоровью",
            },
            {
                value: "+6 ",
                feature: "к регенерации здоровья",
            },
            {
                value: "+2 ",
                feature: "ко всем атрибутам",
            },
            {
                value: "+5 ",
                feature: "к броне",
            },
        ],
        usage: "Guard", 
        description: "На 12 сек. дает героям и постройкам поблизости 2 брони и шанс 100% заблокировать 60 урона от каждой атаки. Способность действует на одно и то же существо не чаще, чем раз в 46 секунд. Радиус 900",
        notation: "С вероятностью в 50% блокирует 70 урона если владелец - герой ближнего боя, или 35 урона, если герой дальнего боя",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "skull basher",
        image: require("image/items/Skull_Basher_icon.png"),
        price: "2700",
        add_stats: [
            {
                value: "+10 ",
                feature: "к силе",
            },
        ],
        usage: "Bash", 
        description: "Каждая атака может оглушить цель на 1.4 сек. и нанести 100 магического урона. От оглушающей атаки нельзя уклониться. Вероятность зависит от типа атаки владельца 25% в ближнем бою, 10% - в дальнем",
        notation: "Не сочетается с другими источниками оглушения, кроме мини-оглушения. Способность Bash не будет работаь у Spirit Breaker, Faceless Void, Slardar и Troll Warlord. Эффект снимается только сильным развеиванием",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "mask of madness",
        image: require("image/items/Mask_of_Madness_icon.png"),
        price: "1975",
        add_stats: [
            {
                value: "+20 ",
                feature: "к урону",
            },
            {
                value: "+10 ",
                feature: "к скорости атаки",
            },
        ],
        usage: "Berserk", 
        description: "Дает владельцу 110 скорости атаки и 12% скорости передвижения, но уменьшает его броню на 8 и запрещает ему применять способности. Действует 8 сек.",
        notation: "Каждая атака восстанавливает владельцу здоровье в размере 15% от нанесенного урона",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "phase boots",
        image: require("image/items/Phase_Boots_icon.png"),
        price: "1240",
        add_stats: [
            {
                value: "+45 ",
                feature: "к скорости передвижения",
            },
            {
                value: "+24 ",
                feature: "к урону",
            },
        ],
        usage: "Phase", 
        description: "Увеличивает скорость передвижения на 24% для героев ближнего боя и на 20% для героев дальнего боя, а также позволяет проходить сквозь существ. Действует 2.5 сек",
        notation: "Основные бонусы к скорости передвижения от нескольких пар ботинок не складываются",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "ring of aquila",
        image: require("image/items/Ring_of_Aquila_(Active)_icon.png"),
        price: "965",
        add_stats: [
            {
                value: "+10 ",
                feature: "к урону",
            },
            {
                value: "+3 ",
                feature: "к силе",
            },
            {
                value: "+9 ",
                feature: "к ловкости",
            },
            {
                value: "+3 ",
                feature: "к интеллекту",
            },
        ],
        usage: "Aquila Aura", 
        description: "Действует на союзников вокруг. Увеличивает восстановление маны на 0.5 и броню на 2. Если выключить способность, аура будет действовать только на героев",
        notation: "не сочетается с аурами Ring of Basilius или Ring of Aquila. Эффекты от нескольких Aquila Aura не складываются",
    },
    {
        base_shop: false,
        secretShop: false,
        sideShop: false,
        title: "solar crest",
        image: require("image/items/Solar_Crest_icon.png"),
        price: "2625",
        add_stats: [
            {
                value: "+10 ",
                feature: "к броне",
            },
            {
                value: "+1 ",
                feature: "к восстановлению маны",
            },
            {
                value: "+20% ",
                feature: "к уклонению",
            },
        ],
        usage: "Shine", 
        description: "Если использовать на союзника, увеличит его броню на 10 и шанс уклонения на 20%. Если использовать на врага, уменьшит его броню на 10 и увеличит точность атак на 40%. Лишает владельца дополнительных брони и уклонения. Не действует на невосприимчивых к магии противника. Дальность приминения 1000",
        notation: "",
    },
    {
        base_shop: false,
        secretShop: false,
        sideShop: false,
        title: "aeon disk",
        image: require("image/items/Aeon_Disk_icon.png"),
        price: "3350",
        add_stats: [
            {
                value: "+250 ",
                feature: "к здоровью",
            },
            {
                value: "+250 ",
                feature: "к мане",
            },
        ],
        usage: "Combo Breaker, Status Resistance", 
        description: "Если здоровье владельца упадет ниже 70%, он получит магический щит, который сильным очищением развеет большинство эффектов и не даст наносить или получать урон следующие 2.5 сек. Срабатывает только от урона существ, подконтрольных игрокам. Уменьшает длительность отрицательных эффектов на 25%",
        notation: "",
    },
    {
        base_shop: false,
        secretShop: false,
        sideShop: false,
        title: "battle fury",
        image: require("image/items/Battle_Fury_icon.png"),
        price: "4100",
        add_stats: [
            {
                value: "+45 ",
                feature: "к урон",
            },
            {
                value: "+6 ",
                feature: "к регенерации здоровья",
            },
            {
                value: "+2.25 ",
                feature: "к восстановлению маны",
            },
        ],
        usage: "Chop Tree/Ward, Quell, Cleave", 
        description: "Уничтожает выбранно дерево или вард. Увеличивает урон от атак по существам, не являющимися героями, на 60% для героевближнего боя и на 25% - для дальнего. Наносит физический урон, равный 40% урона от атак, всем врагам вокруг основной цели (только в ближнем бою)",
        notation: "Урон соседним целям снижается типом брони, но не ее значением. Урон соседним целям проходит через невосприимчивость к магии. Каждый предмет или способность, дарующий прорубающую атаку, наносит урон отдельно друг от друга. Активируемая способность может разрушать бомбы от способности Remote Mines у Techies",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "helm of the dominator",
        image: require("image/items/Helm_of_the_Dominator_icon.png"),
        price: "2000",
        add_stats: [
            {
                value: "+2 ",
                feature: "ко всем атрибутам",
            },
            {
                value: "+5 ",
                feature: "к скорости атаки",
            },
        ],
        usage: "Dominate, Dominator Aura", 
        description: "Дает контроль над нейтральным крипом, не являющимся древним, и увеличивает его скорость передвижения до 425, а запас здоровья до 1500. Если максимальное здоровье существа больше 1500, оно не изменится. За убийство существа дается 125 золота. Аура действует на союзников вокруг. Увеличивает его скорость атаки на 20 и восстановление здоровья на 8",
        notation: "Можно приручить только одно существо. Если приручить новое существо, старое умрет. Так же действует на вражеских крипов с линии и призванных существ. Подчиненное существо умрет, если продать этот предмет",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: true,
        title: "power treads",
        image: require("image/items/Power_Treads_icon.png"),
        price: "1350",
        add_stats: [
            {
                value: "+45 ",
                feature: "к скорости передвижения",
            },
            {
                value: "+10 ",
                feature: "к выбранному атрибуту",
            },
            {
                value: "+25 ",
                feature: "к скорости атаки",
            },
        ],
        usage: "Switch Attribute", 
        description: "Меняет атрибут, который получает бонус +10 силе, ловкости или интеллекту. Основные бонусы к скорости передвижения от нескольких пар не складываются",
        notation: "Power Treads можно собрать, используя Belt of Strength, Band of Elvenskin или Robe of the Magi. Бонус к скорости атаки от нескольких Power Treads не складываются",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "medallion of courage",
        image: require("image/items/Medallion_of_Courage_icon.png"),
        price: "1175",
        add_stats: [
            {
                value: "+7 ",
                feature: "к  броне",
            },
            {
                value: "+0.5 ",
                feature: "к восстановлению маны",
            },
        ],
        usage: "Valor", 
        description: "Если использовать на союзника, снизит броню владельца, но увеличит ее у цели. Если использовать на врага, снизит броню у владельца, и у жертвы. Не действует на невосприимчивых к магии противника.",
        notation: "Эффект можно развеять",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "dagon",
        image: require("image/items/Dagon_1_icon.png"),
        price: "2715",
        add_stats: [
            {
                value: "+15/18/21/24/27 ",
                feature: "к интеллекту",
            },
            {
                value: "+3 ",
                feature: "ко всем атрибутам",
            },
        ],
        usage: "Energy Burst", 
        description: "Выпускает мощный всплеск энергии, наносящий магический урон выбранному вражескому существу. Предмет можно улучшить. Урон 400/500/600/700/800, Дальность 600/650/700/750/800, Расход маны 180",
        notation: "Мгновенно убивает иллюзии",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "black king bar",
        image: require("image/items/Black_King_Bar_icon.png"),
        price: "3975",
        add_stats: [
            {
                value: "+10 ",
                feature: "к силе",
            },
            {
                value: "+24 ",
                feature: "к урону",
            },
        ],
        usage: "Avatar", 
        description: "Дает невосприимчивость к магии и полное сопротивление к магическому урону. Длительность и время перезарядки уменьшаются с каждым использованием. Длительность 10/9/8/7/6/5",
        notation: "Покупка другого Black King Bar не обновит время его действия. Использование Black King Bar снимает некоторые положительные эффекты",
    },
    {
        base_shop: false,
        secretShop: false,
        sideShop: false,
        title: "monkey king bar",
        image: require("image/items/Monkey_King_Bar_icon.png"),
        price: "4200",
        add_stats: [
            {
                value: "+60 ",
                feature: "к скорости атаки",
            },
        ],
        usage: "Mini-Bash", 
        description: "Каждая атака может с вероятностью в 75% пройти сквозь уклонение и нанести 60 дополнительного чистого урона",
        notation: "Не исключает шанс промаха по вражеским постройкам",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "echo sabre",
        image: require("image/items/Echo_Sabre_icon.png"),
        price: "2650",
        add_stats: [
            {
                value: "+10 ",
                feature: "к интеллекту",
            },
            {
                value: "+10 ",
                feature: "к силе",
            },
            {
                value: "+10 ",
                feature: "к скорости атаки",
            },
            {
                value: "+0.75 ",
                feature: "к восстановлению маны",
            },
        ],
        usage: "Echo Strike", 
        description: "Позволяет героям ближнего боя совершить двойную атаку, которая на 0.7 сек. уменьшает скорость передвижения жертвы на 100%.",
        notation: "Эффект можно развеять",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "oblivion staff",
        image: require("image/items/Oblivion_Staff_icon.png"),
        price: "1650",
        add_stats: [
            {
                value: "+10 ",
                feature: "к интеллекту",
            },
            {
                value: "+10 ",
                feature: "к скорости атаки",
            },
            {
                value: "+10 ",
                feature: "+10 к урону",
            },
            {
                value: "+0.75 ",
                feature: "к восстановлению маны",
            },
        ],
        usage: "", 
        description: "",
        notation: "",
    },
    {
        base_shop: false,
        secretShop: false,
        sideShop: true,
        title: "arcane boots",
        image: require("image/items/Arcane_Boots_icon.png"),
        price: "1300",
        add_stats: [
            {
                value: "+50 ",
                feature: "к скорости передвижения",
            },
        ],
        usage: "Replenish Mana", 
        description: "Восстанавливает 135 маны всем союзникам вокруг",
        notation: "Не работает на клонах Meepo",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "eul's scepeter of divinity",
        image: require("image/items/Eul's_Scepter_of_Divinity_icon.png"),
        price: "2750",
        add_stats: [
            {
                value: "+10 ",
                feature: "к интеллекту",
            },
            {
                value: "+2.25 ",
                feature: "к восстановлению маны",
            },
            {
                value: "+40 ",
                feature: "к скорости передвижения",
            },
        ],
        usage: "Cyclone", 
        description: "Поднимает выбранную цель в воздух, делая ее неуязвимой на 2.5 сек. Можно использовать только на себя или противника. Если применить на врага, то по призимлении он получит 50 магического урона.",
        notation: "Нельзя применять на союзников. Использование на себя проходит сквозь невосприимчивость к магии. Cyclone снимает некоторые положительные и отрицательные эффекты. Эффект можно развеять",
    },
    {
        base_shop: false,
        secretShop: true,
        sideShop: false,
        title: "lotus orb",
        image: require("image/items/Lotus_Orb_icon.png"),
        price: "4000",
        add_stats: [
            {
                value: "+10 ",
                feature: "к броне",
            },
            {
                value: "+5.5 ",
                feature: "к регенерации",
            },
            {
                value: "+1.75 ",
                feature: "к восстановлению",
            },
            {
                value: "+250 ",
                feature: "к мане",
            },
        ],
        usage: "Echo Shell", 
        description: "Создает вокруг цели щит, отражающий большинство направленных заклинаний обратно во врага. Действует 6 сек. Не блокирует эффекты вражеских заклинаний.",
        notation: "",
    },
    {
        base_shop: false,
        secretShop: false,
        sideShop: false,
        title: "ethereal blade",
        image: require("image/items/Ethereal_Blade_icon.png"),
        price: "4700",
        add_stats: [
            {
                value: "+40 ",
                feature: "к ловкости",
            },
            {
                value: "+10 ",
                feature: "к силе",
            },
            {
                value: "+10 ",
                feature: "к интеллекту",
            },
        ],
        usage: "Ether Blast", 
        description: "Придает цели бесплотную форму, которая полностью защищает от физического урона, но не позволяет атаковать и увеличивает получаемый магический урон на 40%. Действует 4 сек. на союзников и 3 сек. на врагов. Также замедляет вражескую цель на 80% и наносит ей магический урон в размере 2+ ваш основной атрибут +75.",
        notation: "Имеет общее время перезарядки с Ghost Scepter. Призрачные юниты получают на 4-% больше магического урона. Длится на секунду больше на союзниках и на себе. Использование Town Portal Scroll или Boots of Travel не развеивает бесплотную форму. Эффект можно развеять.",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "maelstorm",
        image: require("image/items/Maelstrom_icon.png"),
        price: "2800",
        add_stats: [
            {
                value: "+24 ",
                feature: "к урону",
            },
            {
                value: "+25 ",
                feature: "скорости атаки",
            },
        ],
        usage: "Chain Lightning", 
        description: "Каждая атака с вероятностью в 25% может создать разряд цепной молнии, которая 4 раза перескочит между случайными врагами в радиусе 900, нанося каждому по 120 магического урона",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: true,
        sideShop: false,
        title: "perseverance",
        image: require("image/items/Perseverance_icon.png"),
        price: "1700",
        add_stats: [
            {
                value: "+5.5 ",
                feature: "регенерации здоровья",
            },
            {
                value: "+1.5 ",
                feature: "к восстановлению маны",
            },
        ],
        usage: "", 
        description: "",
        notation: "Можно передавать союзникам",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "drum of endurance",
        image: require("image/items/Drum_of_Endurance_icon.png"),
        price: "1615",
        add_stats: [
            {
                value: "+6 ",
                feature: "к интеллекту",
            },
            {
                value: "+7 ",
                feature: "к силе",
            },
            {
                value: "+3 ",
                feature: "к ловкости",
            },
            {
                value: "+0.75% ",
                feature: "к восстановлению маны",
            },
        ],
        usage: "Endurance, Swiftness Aura", 
        description: "Активируемая: действует на союзников вокруг. Увеличивает их скорость атаки на 35 и скорость передвижения на 13%. Действует 6 сек. Пассивная: увеличивает союзникам вокруг скорость передвижения на 20.",
        notation: "Покупка рецепта Drum of Endurance восстановит его заряды. Эффект от нескольких Swiftness Aura не складывается. Эффект можно развеять.",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "rod of atos",
        image: require("image/items/Rod_of_Atos_icon.png"),
        price: "3030",
        add_stats: [
            {
                value: "+20 ",
                feature: "к интеллекту",
            },
            {
                value: "+15 ",
                feature: "к силе",
            },
            {
                value: "+6 ",
                feature: "к ловкости",
            },
        ],
        usage: "Cripple", 
        description: "На 2 сек. накладывает на цель оцепенение. Дальность приминения: 1150",
        notation: "Эффект можно развеять",
    },
    {
        base_shop: false,
        secretShop: false,
        sideShop: false,
        title: "shiva's guard",
        image: require("image/items/Shiva's_Guard_icon.png"),
        price: "4750",
        add_stats: [
            {
                value: "+30 ",
                feature: "к интеллекту",
            },
            {
                value: "+15 ",
                feature: "к броне",
            },
        ],
        usage: "Arctic Blast, Freezing Aura", 
        description: "Активируемая: выпускает морозную волну, которая наносит противникам 200 магического урона и на 4 сек. снижает их скорость передвижения на 40%. Радиус 900. Пассивная: снижает скорость атаки противников на 45. Радиус 900",
        notation: "Волна распространяется со скоростью в 350 единиц в секунду до максимального размера в 900 единиц. Морозная волна следуетза владельцем. Эффект от нескольких Freezing Aura не складывается. Эффект можно развеять",
    },
    {
        base_shop: false,
        secretShop: false,
        sideShop: false,
        title: "radiance",
        image: require("image/items/Radiance_(Active)_icon.png"),
        price: "5150",
        add_stats: [
            {
                value: "+65 ",
                feature: "к урону",
            },
        ],
        usage: "Burn", 
        description: "Если включена, каждую секунду наносит противникам 60 магического урона и ослепляет их, вынуждая промахиваться в 17% случаев. Радиус 700",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "diffusal blade",
        image: require("image/items/Diffusal_Blade_1_icon.png"),
        price: "3150",
        add_stats: [
            {
                value: "+20 ",
                feature: "к ловкости",
            },
            {
                value: "+10 ",
                feature: "к интеллекту",
            },
        ],
        usage: "Inhibit, Manabreak", 
        description: "Активируемая: замедляет противника на 4 сек. Дальность приминения 600. Пассивная: каждая атака сжигает 50 маны врага и наносит ему 0.8 физического урона за единицу сожженной маны. Иллюзии героев ближнего боя сжигают по 16 маны за атаку, а дальнего боя - 8.",
        notation: "Не складывается с другими способностями, сжигающими ману. Эффект можно развеять.",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "hand of midas",
        image: require("image/items/Hand_of_Midas_icon.png"),
        price: "2150",
        add_stats: [
            {
                value: "+30 ",
                feature: "к скорости атаки",
            },
        ],
        usage: "Transmute", 
        description: "Убивает выбранную цель (но не героя), давая за нее 200 золота и в 1.85 раза больше опыта. Не действует на древних крипов. Дальность приминения 600",
        notation: "Получаемое золото идет в надежный запас (при этом стандартная награда за убийство крипа не дается). Опыт от убитого крипа не делится с другими героями",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "vladmir's offering",
        image: require("image/items/Vladmir's_Offering_icon.png"),
        price: "2250",
        add_stats: [
            {
                value: "+2 ",
                feature: "ко всем атрибутам",
            },
        ],
        usage: "Vladmir's Aura", 
        description: "Дарует союзникам вокруг эффект вампиризма (15% для героев ближнего боя и 10% - для героев дальнего боя), увеличивает их броню на 4, урон на 15, а также усиливает восстановление здоровья на 2.5 и восстановление маны на 0.65",
        notation: "Эффект от нескольких аур Vladmir's Offering не складывается. Эффекты от нескольких Vladmir's Aura не складываются",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "orchid malevolence",
        image: require("image/items/Orchid_Malevolence_icon.png"),
        price: "4075",
        add_stats: [
            {
                value: "+25 ",
                feature: "к интеллекту",
            },
            {
                value: "+30 ",
                feature: "к скорости атаки",
            },
            {
                value: "+2.25 ",
                feature: "к восстановлению маны",
            },
        ],
        usage: "Soul Burn", 
        description: "Запрещает выбранной цели использовать способности на 5 сек. По окончании эффекта жертве наносится ипгтческий урон в размере 30% от урона, полученного за врем действия. Дальность приминения 900",
        notation: "Эффект можно развеять",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "hurricane pike",
        image: require("image/items/Hurricane_Pike_icon.png"),
        price: "4615",
        add_stats: [
            {
                value: "+13 ",
                feature: "к интеллекту",
            },
            {
                value: "+5.5 ",
                feature: "к регенерации здоровья",
            },
            {
                value: "+20 ",
                feature: "к ловкости",
            },
            {
                value: "+15 ",
                feature: "к силе",
            },
        ],
        usage: "Hurricane thrust", 
        description: "Активируемая: отталкивает вражескую цель и владельца друг от друга на расстояние в 450 единиц. Если владелец сражается в дальнем бою, то после этого он следующие 5 секунд может совершить до 4 атак по цели без ограничения на расстояние. Скорость таких атак увеличена на 100. При использовании на себя или союзников работает как Force Staff. Пассивная: увеличивает дальность атаки героев дальнего боя на 140.",
        notation: "Можно применить на себя. Не прерывает действия цели. Не работает на существ под воздействием способностей Chronosphere, Duel или Black Hole",
    },
    {
        base_shop: false,
        secretShop: false,
        sideShop: false,
        title: "daedalus",
        image: require("image/items/Daedalus_icon.png"),
        price: "5320",
        add_stats: [
            {
                value: "+80 ",
                feature: "к урону",
            },
        ],
        usage: "Critical Strike", 
        description: "Каждая атака может с вероятностью в 30% нанести 235% урона",
        notation: "Постройкам дополнительный урон не наносится",
    },
    {
        base_shop: false,
        secretShop: false,
        sideShop: false,
        title: "heaven's halberd",
        image: require("image/items/Heaven's_Halberd_icon.png"),
        price: "3400",
        add_stats: [
            {
                value: "+25% ",
                feature: "к уклонению",
            },
            {
                value: "+25 ",
                feature: "к урону",
            },
            {
                value: "+20 ",
                feature: "+к силе",
            },
        ],
        usage: "Disarm, Lesser Maim", 
        description: "Активируемая: лишает существо сил, от чего оно не может атаковать. Длительность бессилия зависит от типа атаки жертвы. Дальность 600, Длительность (ближний бой) 3, Длительность (дальний бой) 5. Пассивная: каждая атака с вероятностью в 35% может нанести травму, замедляющую врага в зависимости от его типа атаки. Длительность травмы 5, Замедление (ближний бой): передвижение 20%, атака 20, замедление (дальний бой): передвижение 10%, атака 10",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "boots of travel",
        image: require("image/items/Boots_of_Travel_1_icon.png"),
        price: "2400",
        add_stats: [
            {
                value: "+100 ",
                feature: "к скорости передвижения",
            },
        ],
        usage: "Teleport", 
        description: "Телепортирует к союзной постройке или существу, не являющимся героем. Телепортация к существу прервется, если оно умрет. Имеет общее время перезарядки с Town Portal Scroll",
        notation: "Основные бонусы к скоростипередвижения от нескольких пар ботинок не складываются",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "mekansm",
        image: require("image/items/Mekansm_icon.png"),
        price: "2350",
        add_stats: [
            {
                value: "+5 ",
                feature: "ко всем атрибутам",
            },
            {
                value: "+5 ",
                feature: "к броне",
            },
        ],
        usage: "Restore, Mekansm Aura", 
        description: "Активируемая: действует на союзников в радиусе 900. Восстанавливает 250 здоровья и дает 2 брони. Пассивная: увеличивает восстановление здоровья на 3.5 всем союзникам в радиусе 900",
        notation: "Restore действует на одно и то же существо не чаще, чем раз в 25 секунд. Эффект от нескольких Mekansm Aura не складываются",
    },
    {
        base_shop: false,
        secretShop: false,
        sideShop: false,
        title: "aghanim's scepter",
        image: require("image/items/Aghanim's_Scepter_icon.png"),
        price: "4200",
        add_stats: [
            {
                value: "+10 ",
                feature: "ко всем атрибутам",
            },
            {
                value: "+175 ",
                feature: "к здоровью",
            },
            {
                value: "+175 ",
                feature: "к мане",
            },
        ],
        usage: "Ultimate Upgrade", 
        description: "Улучшает ульт и другие способности некоторых героев",
        notation: "",
    },
    {
        base_shop: false,
        secretShop: false,
        sideShop: false,
        title: "linken's sphere",
        image: require("image/items/Linken's_Sphere_icon.png"),
        price: "5050",
        add_stats: [
            {
                value: "+15 ",
                feature: "ко всем атрибутам",
            },
            {
                value: "+5.5 ",
                feature: "к регенерации здоровья",
            },
            {
                value: "+2.25 ",
                feature: "к восстановлению маны",
            },
        ],
        usage: "Spellblock, Transfer Spellblock", 
        description: "Активируемая: временно отключает пассивную способность предмета, передавая ее выбранному союзнику на 13 сек. Пассивная: блокирует одну направленную способность каждые 13 сек. Некоторые способности не блокируются.",
        notation: "",
    },
    {
        base_shop: false,
        secretShop: false,
        sideShop: false,
        title: "butterfly",
        image: require("image/items/Butterfly_icon.png"),
        price: "5525",
        add_stats: [
            {
                value: "+35 ",
                feature: "к ловкости",
            },
            {
                value: "+25 ",
                feature: "к урону",
            },
            {
                value: "+35% ",
                feature: "к уклонению",
            },
            {
                value: "+30 ",
                feature: "к скорости атаки",
            },
        ],
        usage: "Flutter", 
        description: "Ускоряет передвижение на 35%. Действует 2 сек.",
        notation: "Сочетается по закону убывающей полезности с другими источниками уклонения",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "desolator",
        image: require("image/items/Desolator_icon.png"),
        price: "3500",
        add_stats: [
            {
                value: "+50 ",
                feature: "к урону",
            },
        ],
        usage: "Corruption", 
        description: "Атаки уменьшают броню цели на 6. Эффект длится 15 сек.",
        notation: "Снижение брони действует на здания. Эффект можно развеять",
    },
    {
        base_shop: false,
        secretShop: true,
        sideShop: false,
        title: "moon shard",
        image: require("image/items/Moon_Shard_icon.png"),
        price: "4000",
        add_stats: [
            {
                value: "+120 ",
                feature: "к скорости атаки",
            },
        ],
        usage: "Shade Sight", 
        description: "Использование: поглощает предмет и навсегда увеличивает скорость атаки на 60, а радиус обзора ночью - на 150. Можно поглотить лишь один Moon Shard. Пассивная: увеличивает радиус обзора ночью на 300",
        notation: "Дополнительный ночной обзор работает и во время способности Darkness героя Night Stalker",
    },
    {
        base_shop: false,
        secretShop: false,
        sideShop: false,
        title: "spirit vessel",
        image: require("image/items/Spirit_Vessel_icon.png"),
        price: "2975",
        add_stats: [
            {
                value: "+250 ",
                feature: "к здоровью",
            },
            {
                value: "+30 ",
                feature: "к скорости передвижения",
            },
            {
                value: "+1 ",
                feature: "к восстановлению маны",
            },
            {
                value: "+2 ",
                feature: "ко всем атрибутам",
            },
            {
                value: "+2 ",
                feature: "к броне",
            },
        ],
        usage: "Soul Release", 
        description: "Активируемая: эффект зависит от выбранной цели. Если применить на противника, то он будет терять 3% от своего текущего запаса здоровья, а также получать на 70% меньше здоровья от любого лечения. Помимо этого, способность наносит 20 урона в секунду. Если применить на союзника, то он будет восстанавливать 1% от своего текущего запаса здоровья, а также получать на 20% больше здоровья от любого лечения. Помимо этого, увеличивает восстановление здоровья на 35 в секунду. Получает заряды каждый раз, когда в радиусе 1400 умирает вражеский герой. Заряд получит только один, ближайший к умершему герою предмет.",
        notation: "",
    },
    {
        base_shop: false,
        secretShop: false,
        sideShop: false,
        title: "nullifier",
        image: require("image/items/Nullifier_icon.png"),
        price: "4700",
        add_stats: [
            {
                value: "+65 ",
                feature: "к урону",
            },
            {
                value: "+5 ",
                feature: "к броне",
            },
            {
                value: "+5 ",
                feature: "регенерации здоровья",
            },
        ],
        usage: "Nullify", 
        description: "Развеивает положительные эффекты на цели, а также запрещает ей использовать предметы на 5 сек. Любая атака по цели замедлит ее на 100%. Длительность замедления: 0.4 сек.",
        notation: "",
    },
    {
        base_shop: false,
        secretShop: true,
        sideShop: false,
        title: "bloodstone",
        image: require("image/items/Bloodstone_icon.png"),
        price: "4900",
        add_stats: [
            {
                value: "+475 ",
                feature: "к урону",
            },
            {
                value: "+425 ",
                feature: "к мане",
            },
            {
                value: "+7 ",
                feature: "к регенерации здоровья",
            },
            {
                value: "+2 ",
                feature: "к восстановлению маны",
            },
        ],
        usage: "Pocket Deny, Bloodpact", 
        description: "Активируемая: мгновенно убивает героя. Для использования нужно указать место смерти. Способность нельзя применить на себя. Пассивная: изначально имеет 14 зарядов. Получает заряд каждый раз, когда в радиусе 1600 умирает вражеский герой. Каждый заряд увеличивает восстановление маны на 0.35 и уменьшает время возрождения на 3 сек. При смерти владельца предмет теряет треть зарядов.",
        notation: "Если у героя несколько Bloodstone, заряды будет получать только первый.",
    },
    {
        base_shop: false,
        secretShop: false,
        sideShop: false,
        title: "silver edge",
        image: require("image/items/Silver_Edge_icon.png"),
        price: "5550",
        add_stats: [
            {
                value: "+30 ",
                feature: "к скорости атаки",
            },
            {
                value: "+15 ",
                feature: "ко всем атрибутам",
            },
        ],
        usage: "Shadow Walk", 
        description: "Делает героя невидимым на 14 сек. или до момента, когда он совершит атаку или применит способность. Эффект также увеличивает скорость передвижения на 25% и позволяет проходить сквозь существ. Атака, прерывающая невидимость, дополнительно нанесет 175 физического урона и отключит пассивные способности жертвы. Длительность эффекта 5 сек.",
        notation: "Ударом из невидимости нельзя промахнуться. Не проходит сквозь невосприимчивость к магии.",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "sange and yasha",
        image: require("image/items/Sange_and_Yasha_icon.png"),
        price: "3900",
        add_stats: [
            {
                value: "+16 ",
                feature: "к урону",
            },
            {
                value: "+16 ",
                feature: "к силе",
            },
            {
                value: "+16 ",
                feature: "к ловкости",
            },
            {
                value: "+16 ",
                feature: "к скорости атаки",
            },
            {
                value: "+16 ",
                feature: "к скорости передвижения",
            },
        ],
        usage: "Greater Maim", 
        description: "Каждая атака с вероятностью в 40% может нанести травму, замедляющую врага в зависимости от типа атаки владельца. Длительность травмы 5. Замедление (ближний бой): передвижение 26%, атака 26. Замедление (дальний бой): передвижение 13%, атака 13",
        notation: "Бонусы к скорости от нескольких предметов на основе Yasha не складываются. Эффект можно развеять.",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "pipe of insight",
        image: require("image/items/Pipe_of_Insight_icon.png"),
        price: "3150",
        add_stats: "",
        usage: "Insight Aura", 
        description: "Создает на владельца и окружающих его союзниках барьер, блокирующий 400 магического урона. Действует 12 сек. Пассивная: действует на союзников вокруг. Увеличивает их восстановление здоровья на 2 и сопротивление магии на 10%.",
        notation: "Эффект от нескольких Barrier не складывается. Сочетается по закону убывающей полезности с другими источниками сопротивления магии.",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "refresher orb",
        image: require("image/items/Refresher_Orb_icon.png"),
        price: "5200",
        add_stats: [
            {
                value: "+11 ",
                feature: "к регенерации здоровья",
            },
            {
                value: "+3 ",
                feature: "к восстановлению маны",
            },
        ],
        usage: "Reset", 
        description: "Сбрасывает время перезарядки всех ваших предметов и способностей.",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "manta style",
        image: require("image/items/Manta_Style_icon.png"),
        price: "5000",
        add_stats: [
            {
                value: "+10 ",
                feature: "к силе",
            },
            {
                value: "+26 ",
                feature: "к ловкости",
            },
            {
                value: "+10 ",
                feature: "к интеллекту",
            },
            {
                value: "+10 ",
                feature: "к скорости атаки",
            },
            {
                value: "+8% ",
                feature: "к скорости передвижения",
            },
        ],
        usage: "Mirror Image", 
        description: "Создает 2 иллюзии вашего героя, которые существуют 20 сек. Иллюзии ближнего боя наносят 33% урона и получают 350% урона. Иллюзии дальнего боя наносят 28% урона и получают 400% урона. У героев дальнего боя перезаряжается на 15 сек дольше",
        notation: "Предмет используется 0.1 секунды, во время которой неуязвимы. Использование снимает многие эффекты. Бонусы к скорости от нескольких предметов на основе Yasha не складываются.",
    },
    {
        base_shop: false,
        secretShop: true,
        sideShop: false,
        title: "divine rapier",
        image: require("image/items/Divine_Rapier_icon.png"),
        price: "6000",
        add_stats: [
            {
                value: "+330 ",
                feature: "к урону",
            },
        ],
        usage: "Everlasting", 
        description: "Предмет выпадает при смерти и не иожет быть уничтожен. Если выпавший предмет поднимает союзник владельца, то Divine Rapier потеряет свои свойства, пока его не вернут бывшему владельцу. Если предмет подберет враг, то после его смрети бонусы от Divine Rapier сможет получить кто угодно. Курьер не может подобрать этот предмет, если он выпал при смерти.",
        notation: "Если Divine Rapier поднимает враг ее первого владельца, то она выпадает только при смерти этого врага",
    },
    {
        base_shop: false,
        secretShop: true,
        sideShop: false,
        title: "eye of skadi",
        image: require("image/items/Eye_of_Skadi_icon.png"),
        price: "5500",
        add_stats: [
            {
                value: "+25 ",
                feature: "ко всем атрибутам",
            },
            {
                value: "+225 ",
                feature: "к здоровью",
            },
            {
                value: "+250 ",
                feature: "к мане",
            },
        ],
        usage: "Cold Attack", 
        description: "Каждая атака замедляет скорость передвижения жертвы на 25% и скорость ее атаки на 45. Длительность замедления зависит от типа атаки владельца: в ближнем бою 5 сек, в дальнем - 2.5 сек",
        notation: "Для героев ближнего боя длится 5 секунд, для героев дальнего боя - 2.5 секунды",
    },
    {
        base_shop: false,
        secretShop: false,
        sideShop: false,
        title: "guardian greaves",
        image: require("image/items/Guardian_Greaves_icon.png"),
        price: "5350",
        add_stats: [
            {
                value: "+55 ",
                feature: "к скорости передвижения",
            },
            {
                value: "+250 ",
                feature: "к мане",
            },
            {
                value: "+5 ",
                feature: "ко всем атрибутам",
            },
            {
                value: "+5 ",
                feature: "к броне",
            },
        ],
        usage: "Mend, Guardian Aura", 
        description: "Активируемая: восстанавливает 250 здоровья и 160 маны всем союзникам вокруг, а также снимает с владельца большинство отрицательных эффектов. Радиус 900. Пассивная: действует на союзников вокруг. Увеличивает их восстановление здоровья на 3.5 и броню на 2. Если уровень здоровья союзного героя ниже 20%, то аура будет действовать на него сильнее, восстанавливает 12 здоровья в секунду и увеличивая броню на 15.",
        notation: "Аура усиливается только на героях",
    },
    {
        base_shop: false,
        secretShop: true,
        sideShop: false,
        title: "scythe of vyse",
        image: require("image/items/Scythe_of_Vyse_icon.png"),
        price: "5700",
        add_stats: [
            {
                value: "+10 ",
                feature: "к силе",
            },
            {
                value: "+10 ",
                feature: "к ловкости",
            },
            {
                value: "+35 ",
                feature: "к интеллекту",
            },
            {
                value: "+2.25 ",
                feature: "к восстановлению маны",
            },
        ],
        usage: "Hex", 
        description: "Превращает цель в безобидную зверушку на 3.5 сек. Жертва не может атаковать, применять способности или использовать предметы, а ее базовая скорость падает до 140. Мгновенно уничтожает иллюзии.",
        notation: "Жертва имеет базовую скорость в 140 единиц, но не теряет эффекты, дающие максимальную скорость.",
    },
    {
        base_shop: false,
        secretShop: true,
        sideShop: false,
        title: "heart of tarrasque",
        image: require("image/items/Heart_of_Tarrasque_icon.png"),
        price: "5200",
        add_stats: [
            {
                value: "+40 ",
                feature: "к силе",
            },
            {
                value: "+500 ",
                feature: "к здоровью",
            },
        ],
        usage: "Health Regeneration", 
        description: "Восстанавливает 7% от максимального здоровья в секунду. Если получить урон от вражеского героя или Рошана, способность отключается на 5 сек. для героев ближнего боя или на 7 сек. для героев дальнего боя",
        notation: "",
    },
    {
        base_shop: false,
        secretShop: false,
        sideShop: false,
        title: "abyssal blade",
        image: require("image/items/Abyssal_Blade_icon.png"),
        price: "6400",
        add_stats: [
            {
                value: "+250 ",
                feature: "к здоровью",
            },
            {
                value: "+7 ",
                feature: "к регенерации здоровья",
            },
            {
                value: "+10 ",
                feature: "к силе",
            },
        ],
        usage: "Overwhelm, Bash, Damage Block", 
        description: "Активируемая: оглушает выбранного противника на 2 сек. Проходит сквозь невосприимчивость к магии. Дальность приминения 140. Пассивная: каждая атака может оглушить цель на 1.4 сек. и нанести 100 магического урона. От оглушающей атаки нельзя уклониться. Вероятность зависит от типа атаки владельца 25% в ближнем бою, 10% - в дальнем. Пассивная: с вероятностью в 50% блокирует 70 урона от атак, если владелец - герой ближнего боя, или 35 урона, если герой дальнего боя.",
        notation: "Оглушение наносится на дистанции ближнего боя. Не сочетается с другими оглушениями от ударов. Способность Bash не будет работать у Spirit Breaker, Faceless Void, Slardar и Troll Warlord. Эффекты нескольких способностей, блокирующих урон, не сочетаются. Эффект снимается только сильным развеиванием.",
    },
    {
        base_shop: false,
        secretShop: false,
        sideShop: false,
        title: "satanic",
        image: require("image/items/Satanic_icon.png"),
        price: "5500",
        add_stats: [
            {
                value: "+25 ",
                feature: "к силе",
            },
            {
                value: "+50 ",
                feature: "к урону",
            },
        ],
        usage: "Unholy Rage, Lifesteal", 
        description: "Активируемая: увеличивает эффект вампиризма до 200% на 4.5 сек. Пассивная: каждая атака восстанавливает владельцу здоровье в размере 25% от нанесенного урона",
        notation: "Эффект можно развеять",
    },
    {
        base_shop: false,
        secretShop: true,
        sideShop: false,
        title: "octarine core",
        image: require("image/items/Octarine_Core_icon.png"),
        price: "5900",
        add_stats: [
            {
                value: "+25 ",
                feature: "к интеллекту",
            },
            {
                value: "+425 ",
                feature: "к здоровью",
            },
            {
                value: "+425 ",
                feature: "к мане",
            },
        ],
        usage: "Cooldown Reduction, Spell Lifesteal", 
        description: "Уменьшает время перезарядки всех способностей и предметов на 25%. Дает магический вампиризм, который восстанавливает здоровье за наносимый способностями урон. Восстанавливает здоровье в размере 25% от урона героям и 5% от урона по крипам.",
        notation: "",
    },
    {
        base_shop: false,
        secretShop: false,
        sideShop: false,
        title: "assault cuirass",
        image: require("image/items/Assault_Cuirass_icon.png"),
        price: "5250",
        add_stats: [
            {
                value: "+30 ",
                feature: "к скорости атаки",
            },
            {
                value: "+10 ",
                feature: "к броне",
            },
        ],
        usage: "Assault Aura", 
        description: "Увеличивает броню союзных построек и существ на 5, а их скорость атаки - на 25. Снижает броню врагов поблизости на 5. Радиус 900",
        notation: "Эффект от нескольких Assault Aura не складывается.",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "bloodthorn",
        image: require("image/items/Bloodthorn_icon.png"),
        price: "7195",
        add_stats: [
            {
                value: "+25 ",
                feature: "к интеллекту",
            },
            {
                value: "+30 ",
                feature: "к скорости атаки",
            },
            {
                value: "+60 ",
                feature: "к урону",
            },
            {
                value: "+2.25 ",
                feature: "к восстановлению маны",
            },
        ],
        usage: "Soul Rend, Critical Strike", 
        description: "Активируемая: запрещает выбранной цели использовать способности на 5 сек. По окончании эффекта жертве наносится магический урон в размере 30% от урона, полученного за время действия. По цели невозможно промахнуться, а все атаки по ней наносят 140% урона. Дальность приминения 900. Пассивная: каждая атака может с вероятностью в 20% нанести 175% урона",
        notation: "Постройкам дополнительный урон не наносится. Эффект можно развеять.",
    },
    {
        base_shop: false,
        secretShop: false,
        sideShop: false,
        title: "mjollnir",
        image: require("image/items/Mjollnir_icon.png"),
        price: "5700",
        add_stats: [
            {
                value: "+24 ",
                feature: "к урону",
            },
            {
                value: "+80 ",
                feature: "к скорости атаки",
            },
        ],
        usage: "Static Charge, Chain Lightning", 
        description: "Активируемая: на 15 сек. окружает выбранное существо заряженным щитом, который с вероятностью в 20% может нанести 200 магического урона атакующему врагу и 4 другим. Пассивная: каждая атака с вероятностью в 25% может создать разряд цепной молнии, которая 12 раз перескочит между случайными врагами в радиусе 900, нанося каждому по 150 магического урона.",
        notation: "Срабатывает не чаще, чем раз в секунду. Молнии от способности Static Charge наносят магический урон целям на расстоянии до 900 единиц вокруг существа, на котором находится щит. Молнии от Static Charge не срабатывают на невидимых или скрытых в тумане войны героев. Эффект можно развеять.",
    },
]