export default {
    main_items: {
        town_portal_scroll: {
            image: "image/items/Town_Portal_Scroll_icon.png",
            title: "town portal scroll",
            price: "50",
            add_stats: "",
            usage: "teleport",
            description: "",
            notation: "",
        },
        iron_branch: {
            image: "image/items/Iron_Branch_icon.png",
            title: "iron branch",
            price: "50",
            add_stats: "",
            usage: "plant tree",
            description: "",
            notation: "",
        },
        ring_of_protaction: {
            image: "image/items/Ring_of_Protection_icon.png",
            title: "ring of protaction",
            price: "175",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        magic_stick: {
            image: "image/items/Magic_Stick_icon.png",
            title: "magic stick",
            price: "200",
            add_stats: "",
            usage: "energy charge",
            description: "",
            notation: "",
        },
        bottle: {
            image: "image/items/Bottle_(Full)_icon.png",
            title: "bottle",
            price: "650",
            add_stats: "",
            usage: "regenerate",
            description: "",
            notation: "",
        },
        clarity: {
            image: "image/items/Clarity_icon.png",
            title: "clarity",
            price: "50",
            add_stats: "",
            usage: "replenish",
            description: "",
            notation: "",
        },
        gauntlets_of_strength: {
            image: "image/items/Gauntlets_of_Strength_icon.png",
            title: "gauntlets of strength",
            price: "135",
            add_stats: "",
            usage: "chop tree/ward",
            description: "",
            notation: "",
        },
        stout_shield: {
            image: "image/items/Stout_Shield_icon.png",
            title: "stout shield",
            price: "200",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        wind_lace: {
            image: "image/items/Wind_Lace_icon.png",
            title: "wind lace",
            price: "250",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        ring_of_health: {
            image: "image/items/Ring_of_Health_icon.png",
            title: "ring of health",
            price: "650",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        faerie_fire: {
            image: "image/items/Faerie_Fire_icon.png",
            title: "faerie fire",
            price: "70",
            add_stats: "",
            usage: "imbue",
            description: "",
            notation: "",
        },
        slippers_of_agility: {
            image: "image/items/Slippers_of_Agility_icon.png",
            title: "slippers of agility",
            price: "135",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        quelling_blade: {
            image: "image/items/Quelling_Blade_icon.png",
            title: "quelling blade",
            price: "200",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        ring_of_regen: {
            image: "image/items/Ring_of_Regen_icon.png",
            title: "ring of regen",
            price: "300",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        voide_stone: {
            image: "image/items/Void_Stone_icon.png",
            title: "voide stone",
            price: "850",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        smoke_of_deceit: {
            image: "image/items/Smoke_of_Deceit_icon.png",
            title: "smoke of deceit",
            price: "80",
            add_stats: "",
            usage: "disgulse",
            description: "",
            notation: "",
        },
        mantle_of_intelligence: {
            image: "image/items/Mantle_of_Intelligence_icon.png",
            title: "mantle of intelligence",
            price: "135",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        infused_raindrops: {
            image: "image/items/Infused_Raindrop_icon.png",
            title: "infused raindrops",
            price: "225",
            add_stats: "",
            usage: "magical damage block",
            description: "",
            notation: "",
        },
        sages_mask: {
            image: "image/items/Sages_Mask_icon.png",
            title: "sage's mask",
            price: "325",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        energy_booster: {
            image: "image/items/Energy_Booster_icon.png",
            title: "energy booster",
            price: "900",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        observer_ward: {
            image: "image/items/Observer_Ward_icon.png",
            title: "observer ward",
            price: "80",
            add_stats: "",
            usage: "plant",
            description: "",
            notation: "",
        },
        circlet: {
            image: "image/items/Circlet_icon.png",
            title: "circlet",
            price: "165",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        orb_of_venom: {
            image: "image/items/Orb_of_Venom_icon.png",
            title: "orb of venom",
            price: "275",
            add_stats: "",
            usage: "poison attack",
            description: "",
            notation: "",
        },
        boots_of_speed: {
            image: "image/items/Boots_of_Speed_icon.png",
            title: "boots of speed",
            price: "400",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        vitality_booster: {
            image: "image/items/Vitality_Booster_icon.png",
            title: "vitality booster",
            price: "1100",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        sentry_ward: {
            image: "image/items/Sentry_Ward_icon.png",
            title: "sentry ward",
            price: "100",
            add_stats: "",
            usage: "plant",
            description: "",
            notation: "",
        },
        belt_of_strength: {
            image: "image/items/Belt_of_Strength_icon.png",
            title: "belt of strength",
            price: "450",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        blight_stone: {
            image: "image/items/Blight_Stone_icon.png",
            title: "blight stone",
            price: "300",
            add_stats: "",
            usage: "lesser corruption",
            description: "",
            notation: "",
        },
        gloves_of_haste: {
            image: "image/items/Gloves_of_Haste_icon.png",
            title: "gloves of haste",
            price: "500",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        point_booster: {
            image: "image/items/Point_Booster_icon.png",
            title: "point booster",
            price: "1200",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        enchanted_mango: {
            image: "image/items/Enchanted_Mango_icon.png",
            title: "enchanted mango",
            price: "100",
            add_stats: "",
            usage: "eat mango",
            description: "",
            notation: "",
        },
        band_of_elvenskin: {
            image: "image/items/Band_of_Elvenskin_icon.png",
            title: "band of elvenskin",
            price: "450",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        blades_of_attack: {
            image: "image/items/Blades_of_Attack_icon.png",
            title: "blades of attack",
            price: "420",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        cloak: {
            image: "image/items/Cloak_icon.png",
            title: "cloak",
            price: "550",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        platemail: {
            image: "image/items/Platemail_icon.png",
            title: "platemail",
            price: "1400",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        healing_salve: {
            image: "image/items/Healing_Salve_icon.png",
            title: "healing salve",
            price: "110",
            add_stats: "",
            usage: "salve",
            description: "",
            notation: "",
        },
        robe_of_the_magi: {
            image: "image/items/Robe_of_the_Magi_icon.png",
            title: "robe of the magi",
            price: "450",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        chain_mail: {
            image: "image/items/Chainmail_icon.png",
            title: "chain mail",
            price: "550",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        talisman_of_evasion: {
            image: "image/items/Talisman_of_Evasion_icon.png",
            title: "talisman of evasion",
            price: "1450",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        tango: {
            image: "image/items/Tango_icon.png",
            title: "tango",
            price: "90",
            add_stats: "",
            usage: "devour",
            description: "",
            notation: "",
        },
        ogre_axe: {
            image: "image/items/Ogre_Axe_icon.png",
            title: "ogre axe",
            price: "1000",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        quarterstaff: {
            image: "image/items/Quarterstaff_icon.png",
            title: "quarterstaff",
            price: "875",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        hyperstone: {
            image: "image/items/Hyperstone_icon.png",
            title: "hyperstone",
            price: "2000",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        tome_of_knowledge: {
            image: "image/items/Tome_of_Knowledge_icon.png",
            title: "tome of knowledge",
            price: "150",
            add_stats: "",
            usage: "enlighten",
            description: "",
            notation: "",
        },
        blade_of_alacrity: {
            image: "image/items/Blade_of_Alacrity_icon.png",
            title: "blade of alacrity",
            price: "1000",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        helm_of_iron_will: {
            image: "image/items/Helm_of_Iron_Will_icon.png",
            title: "helm of iron will",
            price: "900",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        gem_of_true_sight: {
            image: "image/items/Gem_of_True_Sight_icon.png",
            title: "gem of true sight",
            price: "900",
            add_stats: "",
            usage: "true sight",
            description: "",
            notation: "",
        },
        ultimate_orb: {
            image: "image/items/Ultimate_Orb_icon.png",
            title: "ultimate orb",
            price: "2150",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        dust_of_appearance: {
            image: "image/items/Dust_of_Appearance_icon.png",
            title: "dust of appearance",
            price: "180",
            add_stats: "",
            usage: "reveal",
            description: "",
            notation: "",
        },
        staff_of_wizardry: {
            image: "image/items/Staff_of_Wizardry_icon.png",
            title: "staff of wizardry",
            price: "1000",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        javelin: {
            image: "image/items/Javelin_icon.png",
            title: "javelin",
            price: "1100",
            add_stats: "",
            usage: "pierce",
            description: "",
            notation: "",
        },
        morbid_mask: {
            image: "image/items/Morbid_Mask_icon.png",
            title: "morbid mask",
            price: "1100",
            add_stats: "",
            usage: "lifesteal",
            description: "",
            notation: "",
        },
        demon_edge: {
            image: "image/items/Demon_Edge_icon.png",
            title: "demon edge",
            price: "2200",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        animal_courier: {
            image: "image/items/Animal_Courier_(Radiant)_icon.png",
            title: "animal courier",
            price: "50",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        broadsword: {
            image: "image/items/Broadsword_icon.png",
            title: "broadsword",
            price: "1200",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        shadow_amulet: {
            image: "image/items/Shadow_Amulet_icon.png",
            title: "shadow amulet",
            price: "1300",
            add_stats: "",
            usage: "fade",
            description: "",
            notation: "",
        },
        mystic_staff: {
            image: "image/items/Mystic_Staff_icon.png",
            title: "mystic staff",
            price: "2700",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        claymore: {
            image: "image/items/Claymore_icon.png",
            title: "claymore",
            price: "1400",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        ghost_scepeter: {
            image: "image/items/Ghost_Scepter_icon.png",
            title: "ghost scepeter",
            price: "1500",
            add_stats: "",
            usage: "ghost form",
            description: "",
            notation: "",
        },
        reaver: {
            image: "image/items/Reaver_icon.png",
            title: "reaver",
            price: "3000",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        mithril_hammer: {
            image: "image/items/Mithril_Hammer_icon.png",
            title: "mithril hammer",
            price: "1600",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        blink_dagger: {
            image: "image/items/Blink_Dagger_icon.png",
            title: "blink dagger",
            price: "2250",
            add_stats: "",
            usage: "blink",
            description: "",
            notation: "",
        },
        eaglesong: {
            image: "image/items/Eaglesong_icon.png",
            title: "eaglesong",
            price: "3200",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
        sacred_relic: {
            image: "image/items/Sacred_Relic_icon.png",
            title: "sacred relic",
            price: "3800",
            add_stats: "",
            usage: "",
            description: "",
            notation: "",
        },
    },
    improved_items: {

    },
}
