export default {
    main_items: {
        town_portal_scroll: {
            image: "image/items/Town_Portal_Scroll_icon.png",
            title: "town portal scroll",
            price: "50",
            add_stats: "",
            usage: "teleport",
            description: "После 3 сек. произнесения заклинания, телепортирует героя к выбранной союзной постройке. При двойном нажатии телепортирует к фонтану своей команды",
            notation: "",
        },
        iron_branch: {
            image: "image/items/Iron_Branch_icon.png",
            title: "iron branch",
            price: "50",
            add_stats: "+1 ко всем аттрибутам",
            usage: "plant tree",
            description: "Садит в указанное место маленькое счастливое деревце, которое исчезнет через 20 сек.",
            notation: "Дальность применения: 200",
        },
        ring_of_protaction: {
            image: "image/items/Ring_of_Protection_icon.png",
            title: "ring of protaction",
            price: "175",
            add_stats: "+2 к броне",
            usage: "",
            description: "",
            notation: "",
        },
        magic_stick: {
            image: "image/items/Magic_Stick_icon.png",
            title: "magic stick",
            price: "200",
            add_stats: "",
            usage: "energy charge",
            description: "Мгновенно восстанавливает 15 здоровья и маны за каждый имеющийся заряд. Может иметь до 10 зарядов. Получает один заряд каждый раз, когда видимый враг в радиусе 1200 использует способность.",
            notation: "",
        },
        bottle: {
            image: "image/items/Bottle_(Full)_icon.png",
            title: "bottle",
            price: "650",
            add_stats: "",
            usage: "regenerate",
            description: "Тратит один заряд, чтобы постепенно восстанавливать цель 80 здоровья и 40 маны на протяжении 2.5 сек. Восстановление прекращается при получении урона от вражеского героя или Рошана. Заряды можно пополнить возле союзного фонтана. Зажмите Ctrl, чтобы применить на союзника. Далность применения: 350",
            notation: "В бутыль можно поместить одну руну, чтобы воспользоваться ей позже. Помещеная в бутыль руна задействуется сама спустя 2 минуты. Руны усиления полностью наполняют бутыль. Руны богатства дают лишь 2 заряда из 3",
        },
        clarity: {
            image: "image/items/Clarity_icon.png",
            title: "clarity",
            price: "50",
            add_stats: "",
            usage: "replenish",
            description: "Увеличивает восстановление маны выбранного существа на 3.2. Действует 50 сек. Восстановление прекращается, если получить урон от вражеского героя или Рошана.",
            notation: "Длительность применения: 50 сек.",
        },
        gauntlets_of_strength: {
            image: "image/items/Gauntlets_of_Strength_icon.png",
            title: "gauntlets of strength",
            price: "135",
            add_stats: "+3 к силе",
            usage: "chop tree/ward",
            description: "",
            notation: "",
        },
        stout_shield: {
            image: "image/items/Stout_Shield_icon.png",
            title: "stout shield",
            price: "200",
            add_stats: "",
            usage: "",
            description: "С верояностью 50% блокирует 18 урона, если владелец - герой ближнего боя, или 9 урона, если герой дальнего боя.",
            notation: "",
        },
        wind_lace: {
            image: "image/items/Wind_Lace_icon.png",
            title: "wind lace",
            price: "250",
            add_stats: "+20 к скорости передвижения.",
            usage: "",
            description: "Бонусы к скорости от нескольких Wind Lace не складываются",
            notation: "",
        },
        ring_of_health: {
            image: "image/items/Ring_of_Health_icon.png",
            title: "ring of health",
            price: "650",
            add_stats: "+5 к регенерации здоровья",
            usage: "",
            description: "",
            notation: "",
        },
        faerie_fire: {
            image: "image/items/Faerie_Fire_icon.png",
            title: "faerie fire",
            price: "70",
            add_stats: "+2 к урону",
            usage: "imbue",
            description: "Мгновенно восстанавливает 85 здоровья.",
            notation: "",
        },
        slippers_of_agility: {
            image: "image/items/Slippers_of_Agility_icon.png",
            title: "slippers of agility",
            price: "135",
            add_stats: "+3 к ловкости",
            usage: "",
            description: "",
            notation: "",
        },
        quelling_blade: {
            image: "image/items/Quelling_Blade_icon.png",
            title: "quelling blade",
            price: "200",
            add_stats: "",
            usage: "",
            description: "Активируемая: уничтажает мгновенно выбранное дерево или вард. Пассивная: увеличивает урон от атак по существам, не являющимися героями, на 24 для героев ближнего боя и на 7 - для дальнего.",
            notation: "",
        },
        ring_of_regen: {
            image: "image/items/Ring_of_Regen_icon.png",
            title: "ring of regen",
            price: "300",
            add_stats: "+1.5 к регенерации здоровья.",
            usage: "",
            description: "",
            notation: "",
        },
        voide_stone: {
            image: "image/items/Void_Stone_icon.png",
            title: "voide stone",
            price: "850",
            add_stats: "+1 к восстановлению маны.",
            usage: "",
            description: "",
            notation: "",
        },
        smoke_of_deceit: {
            image: "image/items/Smoke_of_Deceit_icon.png",
            title: "smoke of deceit",
            price: "80",
            add_stats: "",
            usage: "disgulse",
            description: "Все подконтрольные игрокам существа и герои в радиусе 1200 на 35 секунд становятся невидимыми, а скорость их передвижения увеличивается на 15%. Если совершить атаку или приблизиться к вражескому герою или башне на расстояние в 1025, то невидимость раскроется. Невидимость от этого предмета не расскрывается эффектом True Sight.",
            notation: "",
        },
        mantle_of_intelligence: {
            image: "image/items/Mantle_of_Intelligence_icon.png",
            title: "mantle of intelligence",
            price: "135",
            add_stats: "+3 к интеллекту",
            usage: "",
            description: "",
            notation: "",
        },
        infused_raindrops: {
            image: "image/items/Infused_Raindrop_icon.png",
            title: "infused raindrops",
            price: "225",
            add_stats: "+0.5 к восстановлению маны",
            usage: "magical damage block",
            description: "Теряе один заряд и блокирует до 120 магического урона. Срабатывает, только если урон был больше 50. Изначально имеет 5 зарядов и пропадает вместе с последним из них.",
            notation: "",
        },
        sages_mask: {
            image: "image/items/Sages_Mask_icon.png",
            title: "sage's mask",
            price: "325",
            add_stats: "+0.5 к восстановлению маны",
            usage: "",
            description: "",
            notation: "",
        },
        energy_booster: {
            image: "image/items/Energy_Booster_icon.png",
            title: "energy booster",
            price: "900",
            add_stats: "+250 к мане",
            usage: "",
            description: "",
            notation: "",
        },
        observer_ward: {
            image: "image/items/Observer_Ward_icon.png",
            title: "observer ward",
            price: "80",
            add_stats: "",
            usage: "plant",
            description: "Устанавливает невидимого дозорного - вард, который дает наземный обзор в радиусе 1600. Действует 6 мин. Можно передать один вард союзному герою, зажав клавишу Ctrl.",
            notation: "Дальность применения: 500",
        },
        circlet: {
            image: "image/items/Circlet_icon.png",
            title: "circlet",
            price: "165",
            add_stats: "+2 ко всем аттрибутам",
            usage: "",
            description: "",
            notation: "",
        },
        orb_of_venom: {
            image: "image/items/Orb_of_Venom_icon.png",
            title: "orb of venom",
            price: "275",
            add_stats: "",
            usage: "poison attack",
            description: "Отравляет цель атаки на 3 сек, нанося ей 5 магического урона в секунду и замедляя ее передвижение. Замедление зависит от типа атаки владельца: в ближнем бою 12%, в дальнем - 4%.",
            notation: "",
        },
        boots_of_speed: {
            image: "image/items/Boots_of_Speed_icon.png",
            title: "boots of speed",
            price: "400",
            add_stats: "+40 к скорости передвижения",
            usage: "",
            description: "",
            notation: "",
        },
        vitality_booster: {
            image: "image/items/Vitality_Booster_icon.png",
            title: "vitality booster",
            price: "1100",
            add_stats: "+250 к здоровью",
            usage: "",
            description: "",
            notation: "",
        },
        sentry_ward: {
            image: "image/items/Sentry_Ward_icon.png",
            title: "sentry ward",
            price: "100",
            add_stats: "",
            usage: "plant",
            description: "Устанавливает невидимого дозорного - варда, который имеет способность True Sight, в радиусе 850 раскрывающую невидимых существ и варды в вашей видимости. Действует 4 мин. Не дает наземный обзор. Можно передать один вард союзному герою, зажав клавишу Ctrl.",
            notation: "Дальность установки: 500",
        },
        belt_of_strength: {
            image: "image/items/Belt_of_Strength_icon.png",
            title: "belt of strength",
            price: "450",
            add_stats: "+6 к силе",
            usage: "",
            description: "",
            notation: "",
        },
        blight_stone: {
            image: "image/items/Blight_Stone_icon.png",
            title: "blight stone",
            price: "300",
            add_stats: "",
            usage: "lesser corruption",
            description: "Атаки уменьшают броню цели на 2. Эффект длится 8 сек.",
            notation: "",
        },
        gloves_of_haste: {
            image: "image/items/Gloves_of_Haste_icon.png",
            title: "gloves of haste",
            price: "500",
            add_stats: "+20 к скорости атаки",
            usage: "",
            description: "",
            notation: "",
        },
        point_booster: {
            image: "image/items/Point_Booster_icon.png",
            title: "point booster",
            price: "1200",
            add_stats: "+175 к мане, +175 к здоровью",
            usage: "",
            description: "",
            notation: "",
        },
        enchanted_mango: {
            image: "image/items/Enchanted_Mango_icon.png",
            title: "enchanted mango",
            price: "100",
            add_stats: "+1 к регенерации здоровья",
            usage: "eat mango",
            description: "Мгновенно восстанавливает 175 маны.",
            notation: "Дальности применения: 400",
        },
        band_of_elvenskin: {
            image: "image/items/Band_of_Elvenskin_icon.png",
            title: "band of elvenskin",
            price: "450",
            add_stats: "+6 к ловкости",
            usage: "",
            description: "",
            notation: "",
        },
        blades_of_attack: {
            image: "image/items/Blades_of_Attack_icon.png",
            title: "blades of attack",
            price: "420",
            add_stats: "+9 к урону",
            usage: "",
            description: "",
            notation: "",
        },
        cloak: {
            image: "image/items/Cloak_icon.png",
            title: "cloak",
            price: "550",
            add_stats: "+15% к сопротивлению магии",
            usage: "",
            description: "",
            notation: "",
        },
        platemail: {
            image: "image/items/Platemail_icon.png",
            title: "platemail",
            price: "1400",
            add_stats: "+10 к броне",
            usage: "",
            description: "",
            notation: "",
        },
        healing_salve: {
            image: "image/items/Healing_Salve_icon.png",
            title: "healing salve",
            price: "110",
            add_stats: "",
            usage: "salve",
            description: "Постепенно восстанавливает выбранному существу 50 здоровья на протяжении 8 сек. Восстановление прекращается, если получить урон от вражеского героя или Рошана.",
            notation: "Дальность приминения: 250",
        },
        robe_of_the_magi: {
            image: "image/items/Robe_of_the_Magi_icon.png",
            title: "robe of the magi",
            price: "450",
            add_stats: "+6 к интеллекту",
            usage: "",
            description: "",
            notation: "",
        },
        chain_mail: {
            image: "image/items/Chainmail_icon.png",
            title: "chain mail",
            price: "550",
            add_stats: "+5 к броне",
            usage: "",
            description: "",
            notation: "",
        },
        talisman_of_evasion: {
            image: "image/items/Talisman_of_Evasion_icon.png",
            title: "talisman of evasion",
            price: "1450",
            add_stats: "+20% к уклонению",
            usage: "",
            description: "",
            notation: "",
        },
        tango: {
            image: "image/items/Tango_icon.png",
            title: "tango",
            price: "90",
            add_stats: "",
            usage: "devour",
            description: "Съедает дерево, увеличивая восстановление здоровья на 7. Действует 16 сек. Если съесть вард или деревце от Iron Branch, то восстановится в два раза больше здоровья. Изначально имеет 3 заряда. Можно применить на союзного героя, чтобы дать ему один Tango.",
            notation: "Дальность поедания дерева - 165, варда - 450",
        },
        ogre_axe: {
            image: "image/items/Ogre_Axe_icon.png",
            title: "ogre axe",
            price: "1000",
            add_stats: "",
            usage: "",
            description: "+10 к силе",
            notation: "",
        },
        quarterstaff: {
            image: "image/items/Quarterstaff_icon.png",
            title: "quarterstaff",
            price: "875",
            add_stats: "+10 к урону, +10 к скорости атаки",
            usage: "",
            description: "",
            notation: "",
        },
        hyperstone: {
            image: "image/items/Hyperstone_icon.png",
            title: "hyperstone",
            price: "2000",
            add_stats: "+55 к скорости атаки",
            usage: "",
            description: "",
            notation: "",
        },
        tome_of_knowledge: {
            image: "image/items/Tome_of_Knowledge_icon.png",
            title: "tome of knowledge",
            price: "150",
            add_stats: "",
            usage: "enlighten",
            description: "Дает 500 базового опыта +135 за каждое предыдущее применение этого предмета в вашей команде.",
            notation: "",
        },
        blade_of_alacrity: {
            image: "image/items/Blade_of_Alacrity_icon.png",
            title: "blade of alacrity",
            price: "1000",
            add_stats: "+10 к ловкости",
            usage: "",
            description: "",
            notation: "",
        },
        helm_of_iron_will: {
            image: "image/items/Helm_of_Iron_Will_icon.png",
            title: "helm of iron will",
            price: "900",
            add_stats: "+5 к броне, +3 к регенирации здоровья",
            usage: "",
            description: "",
            notation: "",
        },
        gem_of_true_sight: {
            image: "image/items/Gem_of_True_Sight_icon.png",
            title: "gem of true sight",
            price: "900",
            add_stats: "",
            usage: "true sight",
            description: "Дает владельцу и его союзникам возможность видеть невидимых существ и варды в радиусе 900. Предмет выпадает при смерте и не может быть уничтожен.",
            notation: "",
        },
        ultimate_orb: {
            image: "image/items/Ultimate_Orb_icon.png",
            title: "ultimate orb",
            price: "2150",
            add_stats: "+10 ко всем аттрибутам",
            usage: "",
            description: "",
            notation: "",
        },
        dust_of_appearance: {
            image: "image/items/Dust_of_Appearance_icon.png",
            title: "dust of appearance",
            price: "180",
            add_stats: "",
            usage: "reveal",
            description: "Делает всех невидимых героев в радиусе 1050 видимыми и замедляет их на 20%. Эффект длится 12 сек.",
            notation: "",
        },
        staff_of_wizardry: {
            image: "image/items/Staff_of_Wizardry_icon.png",
            title: "staff of wizardry",
            price: "1000",
            add_stats: "+10 к интеллекту",
            usage: "",
            description: "",
            notation: "",
        },
        javelin: {
            image: "image/items/Javelin_icon.png",
            title: "javelin",
            price: "1100",
            add_stats: "",
            usage: "pierce",
            description: "Каждая атака может с вероятностью в 25% пройти сквозь уклонение и нанести 100 магического урона",
            notation: "",
        },
        morbid_mask: {
            image: "image/items/Morbid_Mask_icon.png",
            title: "morbid mask",
            price: "1100",
            add_stats: "+10 к урону",
            usage: "lifesteal",
            description: "Каждая атака восстанавливает владельцу здоровье в размере 15% от нанесенного урона.",
            notation: "",
        },
        demon_edge: {
            image: "image/items/Demon_Edge_icon.png",
            title: "demon edge",
            price: "2200",
            add_stats: "+42 к урону",
            usage: "",
            description: "",
            notation: "",
        },
        animal_courier: {
            image: "image/items/Animal_Courier_(Radiant)_icon.png",
            title: "animal courier",
            price: "50",
            add_stats: "",
            usage: "",
            description: "Создает существо, которое переносит вещи на базу и обратно",
            notation: "",
        },
        broadsword: {
            image: "image/items/Broadsword_icon.png",
            title: "broadsword",
            price: "1200",
            add_stats: "+18 к урону",
            usage: "",
            description: "",
            notation: "",
        },
        shadow_amulet: {
            image: "image/items/Shadow_Amulet_icon.png",
            title: "shadow amulet",
            price: "1300",
            add_stats: "+20 к скорости атаки",
            usage: "fade",
            description: "Накладывает на героя или выбранного союзника невидимость, которая действует, пока цель стоит на месте. Цель входит в невидимость за 1.25 сек. и мгновенно мгновенно выходит из нее при передвижении. Не начинает перезаряжаться, если применить на себя.",
            notation: "Дальность применения: 600",
        },
        mystic_staff: {
            image: "image/items/Mystic_Staff_icon.png",
            title: "mystic staff",
            price: "2700",
            add_stats: "+25 к интеллекту",
            usage: "",
            description: "",
            notation: "",
        },
        claymore: {
            image: "image/items/Claymore_icon.png",
            title: "claymore",
            price: "1400",
            add_stats: "+21 к урону",
            usage: "",
            description: "",
            notation: "",
        },
        ghost_scepeter: {
            image: "image/items/Ghost_Scepter_icon.png",
            title: "ghost scepeter",
            price: "1500",
            add_stats: "+5 ко всем аттрибутам",
            usage: "ghost form",
            description: "Придает владельцу бесплотную форму, в которой он полностью защищен от физического урона, но не может атаковать и получает на 40% больше магического урона. Действует 4 сек.",
            notation: "",
        },
        reaver: {
            image: "image/items/Reaver_icon.png",
            title: "reaver",
            price: "3000",
            add_stats: "+25 к силе",
            usage: "",
            description: "",
            notation: "",
        },
        mithril_hammer: {
            image: "image/items/Mithril_Hammer_icon.png",
            title: "mithril hammer",
            price: "1600",
            add_stats: "+24 к урону",
            usage: "",
            description: "",
            notation: "",
        },
        blink_dagger: {
            image: "image/items/Blink_Dagger_icon.png",
            title: "blink dagger",
            price: "2250",
            add_stats: "",
            usage: "blink",
            description: "Телепортирует к указанной точке на расстоянии до 1200 единиц. предмет нельзя использовать, если последние 3 сек. его владелец получал урон от вражеских героев или Рошана.",
            notation: "",
        },
        eaglesong: {
            image: "image/items/Eaglesong_icon.png",
            title: "eaglesong",
            price: "3200",
            add_stats: "+25 к ловкости",
            usage: "",
            description: "",
            notation: "",
        },
        sacred_relic: {
            image: "image/items/Sacred_Relic_icon.png",
            title: "sacred relic",
            price: "3800",
            add_stats: "+60 к урону",
            usage: "",
            description: "",
            notation: "",
        },
    },
    improved_items: {

    },
}
