export default [
    {
        base_shop: true,
        secretShop: false,
        sideShop: true,
        title: "town portal scroll",
        image: require("image/items/Town_Portal_Scroll_icon.png"),
        price: "50",
        add_stats: [],
        usage: "teleport",
        description: "После 3 сек. произнесения заклинания, телепортирует героя к выбранной союзной постройке. При двойном нажатии телепортирует к фонтану своей команды",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "iron branch",
        image: require("image/items/Iron_Branch_icon.png"),
        price: "50",
        add_stats: [{
            value: "+1 ",
            feature: "ко всем атрибутам",
        }],
        usage: "plant tree",
        description: "Садит в указанное место маленькое счастливое деревце, которое исчезнет через 20 сек.",
        notation: "Дальность применения: 200",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: true,
        title: "ring of protaction",
        image: require("image/items/Ring_of_Protection_icon.png"),
        price: "175",
        add_stats: [{
            value: "+2 ",
            feature: "к броне",
        }],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: true,
        title: "magic stick",
        image: require("image/items/Magic_Stick_icon.png"),
        price: "200",
        add_stats: [],
        usage: "energy charge",
        description: "Мгновенно восстанавливает 15 здоровья и маны за каждый имеющийся заряд. Может иметь до 10 зарядов. Получает один заряд каждый раз, когда видимый враг в радиусе 1200 использует способность.",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: true,
        sideShop: false,
        title: "bottle",
        image: require("image/items/Bottle_(Full)_icon.png"),
        price: "650",
        add_stats: [],
        usage: "regenerate",
        description: "Тратит один заряд, чтобы постепенно восстанавливать цель 80 здоровья и 40 маны на протяжении 2.5 сек. Восстановление прекращается при получении урона от вражеского героя или Рошана. Заряды можно пополнить возле союзного фонтана. Зажмите Ctrl, чтобы применить на союзника. Далность применения: 350",
        notation: "В бутыль можно поместить одну руну, чтобы воспользоваться ей позже. Помещеная в бутыль руна задействуется сама спустя 2 минуты. Руны усиления полностью наполняют бутыль. Руны богатства дают лишь 2 заряда из 3",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "clarity",
        image: require("image/items/Clarity_icon.png"),
        price: "50",
        add_stats: [],
        usage: "replenish",
        description: "Увеличивает восстановление маны выбранного существа на 3. Действует 50 сек. Восстановление прекращается, если получить урон от вражеского героя или Рошана.",
        notation: "Длительность применения: 50 сек.",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "gauntlets of strength",
        image: require("image/items/Gauntlets_of_Strength_icon.png"),
        price: "135",
        add_stats: [{
            value: "+3 ",
            feature: "к силе",
        }],
        usage: "chop tree/ward",
        description: "",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "stout shield",
        image: require("image/items/Stout_Shield_icon.png"),
        price: "200",
        add_stats: [],
        usage: "",
        description: "С верояностью 50% блокирует 18 урона, если владелец - герой ближнего боя, или 9 урона, если герой дальнего боя.",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "wind lace",
        image: require("image/items/Wind_Lace_icon.png"),
        price: "250",
        add_stats: [{
            value: "+20 ",
            feature: "к скорости передвижения.",
        }],
        usage: "",
        description: "Бонусы к скорости от нескольких Wind Lace не складываются",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: true,
        sideShop: false,
        title: "ring of health",
        image: require("image/items/Ring_of_Health_icon.png"),
        price: "650",
        add_stats: [{
            value: "+5 ",
            feature: "к регенерации здоровья",
        }],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "faerie fire",
        image: require("image/items/Faerie_Fire_icon.png"),
        price: "70",
        add_stats: [{
            value: "+2 ",
            feature: "к урону",
        }],
        usage: "imbue",
        description: "Мгновенно восстанавливает 85 здоровья.",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "slippers of agility",
        image: require("image/items/Slippers_of_Agility_icon.png"),
        price: "135",
        add_stats: [{
            value: "+3 ",
            feature: "к ловкости",
        }],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: true,
        title: "quelling blade",
        image: require("image/items/Quelling_Blade_icon.png"),
        price: "200",
        add_stats: [],
        usage: "",
        description: "Активируемая: уничтажает мгновенно выбранное дерево или вард. Пассивная: увеличивает урон от атак по существам, не являющимися героями, на 24 для героев ближнего боя и на 7 - для дальнего.",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "ring of regen",
        image: require("image/items/Ring_of_Regen_icon.png"),
        price: "300",
        add_stats: [{
            value: "+1.5 ",
            feature: "к регенерации здоровья.",
        }],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: true,
        sideShop: true,
        title: "voide stone",
        image: require("image/items/Void_Stone_icon.png"),
        price: "850",
        add_stats: [{
            value: "+1 ",
            feature: "к восстановлению маны.",
        }],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "smoke of deceit",
        image: require("image/items/Smoke_of_Deceit_icon.png"),
        price: "80",
        add_stats: [],
        usage: "disgulse",
        description: "Все подконтрольные игрокам существа и герои в радиусе 1200 на 35 секунд становятся невидимыми, а скорость их передвижения увеличивается на 15%. Если совершить атаку или приблизиться к вражескому герою или башне на расстояние в 1025, то невидимость раскроется. Невидимость от этого предмета не расскрывается эффектом True Sight.",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "mantle of intelligence",
        image: require("image/items/Mantle_of_Intelligence_icon.png"),
        price: "135",
        add_stats: [{
            value: "+3 ",
            feature: "к интеллекту",
        }],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "infused raindrops",
        image: require("image/items/Infused_Raindrop_icon.png"),
        price: "225",
        add_stats: [{
            value: "+0.5 ",
            feature: "к восстановлению маны",
        }],
        usage: "magical damage block",
        description: "Теряет один заряд и блокирует до 120 магического урона. Срабатывает, только если урон был больше 50. Изначально имеет 5 зарядов и пропадает вместе с последним из них.",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "sage's mask",
        image: require("image/items/Sages_Mask_icon.png"),
        price: "325",
        add_stats: [{
            value: "+0.5 ",
            feature: "к восстановлению маны",
        }],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: false,
        secretShop: true,
        sideShop: true,
        title: "energy booster",
        image: require("image/items/Energy_Booster_icon.png"),
        price: "900",
        add_stats: [{
            value: "+250 ",
            feature: "к мане",
        }],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "observer ward",
        image: require("image/items/Observer_Ward_icon.png"),
        price: "80",
        add_stats: [],
        usage: "plant",
        description: "Устанавливает невидимого дозорного - вард, который дает наземный обзор в радиусе 1600. Действует 6 мин. Можно передать один вард союзному герою, зажав клавишу Ctrl.",
        notation: "Дальность применения: 500",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "circlet",
        image: require("image/items/Circlet_icon.png"),
        price: "165",
        add_stats: [{
            value: "+2 ",
            feature: "ко всем атрибутам",
        }],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "orb of venom",
        image: require("image/items/Orb_of_Venom_icon.png"),
        price: "275",
        add_stats: [],
        usage: "poison attack",
        description: "Отравляет цель атаки на 3 сек, нанося ей 5 магического урона в секунду и замедляя ее передвижение. Замедление зависит от типа атаки владельца: в ближнем бою 12%, в дальнем - 4%.",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: true,
        title: "boots of speed",
        image: require("image/items/Boots_of_Speed_icon.png"),
        price: "500",
        add_stats: [{
            value: "+50 ",
            feature: "к скорости передвижения",
        }],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: false,
        secretShop: true,
        sideShop: true,
        title: "vitality booster",
        image: require("image/items/Vitality_Booster_icon.png"),
        price: "1100",
        add_stats: [{
            value: "+250 ",
            feature: "к здоровью",
        }],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "sentry ward",
        image: require("image/items/Sentry_Ward_icon.png"),
        price: "100",
        add_stats: [],
        usage: "plant",
        description: "Устанавливает невидимого дозорного - варда, который имеет способность True Sight, в радиусе 850 раскрывающую невидимых существ и варды в вашей видимости. Действует 4 мин. Не дает наземный обзор. Можно передать один вард союзному герою, зажав клавишу Ctrl.",
        notation: "Дальность установки: 500",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: true,
        title: "belt of strength",
        image: require("image/items/Belt_of_Strength_icon.png"),
        price: "450",
        add_stats: [{
            value: "+6 ",
            feature: "к силе",
        }],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "blight stone",
        image: require("image/items/Blight_Stone_icon.png"),
        price: "300",
        add_stats: [],
        usage: "lesser corruption",
        description: "Атаки уменьшают броню цели на 2. Эффект длится 8 сек.",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: true,
        title: "gloves of haste",
        image: require("image/items/Gloves_of_Haste_icon.png"),
        price: "500",
        add_stats: [{
            value: "+20 ",
            feature: "к скорости атаки",
        }],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: false,
        secretShop: true,
        sideShop: false,
        title: "point booster",
        image: require("image/items/Point_Booster_icon.png"),
        price: "1200",
        add_stats: [
            {
                value: "+175 ",
                feature: "к мане",
            },
            {
                value: "+175 ",
                feature: "к здоровью",
            }
        ],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "enchanted mango",
        image: require("image/items/Enchanted_Mango_icon.png"),
        price: "100",
        add_stats: [{
            value: "+1 ",
            feature: "к регенерации здоровья",
        }],
        usage: "eat mango",
        description: "Мгновенно восстанавливает 175 маны.",
        notation: "Дальности применения: 400",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: true,
        title: "band of elvenskin",
        image: require("image/items/Band_of_Elvenskin_icon.png"),
        price: "450",
        add_stats: [{
            value: "+6 ",
            feature: "к ловкости",
        }],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "blades of attack",
        image: require("image/items/Blades_of_Attack_icon.png"),
        price: "420",
        add_stats: [{
            value: "+9 ",
            feature: "к урону",
        }],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: true,
        title: "cloak",
        image: require("image/items/Cloak_icon.png"),
        price: "550",
        add_stats: [{
            value: "+15% ",
            feature: "к сопротивлению магии",
        }],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: false,
        secretShop: true,
        sideShop: false,
        title: "platemail",
        image: require("image/items/Platemail_icon.png"),
        price: "1400",
        add_stats: [{
            value: "+10 ",
            feature: "к броне",
        }],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "healing salve",
        image: require("image/items/Healing_Salve_icon.png"),
        price: "110",
        add_stats: [],
        usage: "salve",
        description: "Постепенно восстанавливает выбранному существу 50 здоровья на протяжении 8 сек. Восстановление прекращается, если получить урон от вражеского героя или Рошана.",
        notation: "Дальность приминения: 250",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: true,
        title: "robe of the magi",
        image: require("image/items/Robe_of_the_Magi_icon.png"),
        price: "450",
        add_stats: [{
            value: "+6 ",
            feature: "к интеллекту",
        }],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: true,
        title: "chain mail",
        image: require("image/items/Chainmail_icon.png"),
        price: "550",
        add_stats: [{
            value: "+5 ",
            feature: "к броне",
        }],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: false,
        secretShop: true,
        sideShop: false,
        title: "talisman of evasion",
        image: require("image/items/Talisman_of_Evasion_icon.png"),
        price: "1450",
        add_stats: [{
            value: "+20% ",
            feature: "к уклонению",
        }],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "tango",
        image: require("image/items/Tango_icon.png"),
        price: "90",
        add_stats: [],
        usage: "devour",
        description: "Съедает дерево, увеличивая восстановление здоровья на 7. Действует 16 сек. Если съесть вард или деревце от Iron Branch, то восстановится в два раза больше здоровья. Изначально имеет 3 заряда. Можно применить на союзного героя, чтобы дать ему один Tango.",
        notation: "Дальность поедания дерева - 165, варда - 450",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "ogre axe",
        image: require("image/items/Ogre_Axe_icon.png"),
        price: "1000",
        add_stats: [],
        usage: "",
        description: "+10 к силе",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "quarterstaff",
        image: require("image/items/Quarterstaff_icon.png"),
        price: "875",
        add_stats: [
            {
                value: "+10 ",
                feature: "к урону,",
            },
            {
                value: "+10 ",
                feature: "к скорости атаки",
            }
        ],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: false,
        secretShop: true,
        sideShop: false,
        title: "hyperstone",
        image: require("image/items/Hyperstone_icon.png"),
        price: "2000",
        add_stats: [{
            value: "+55 ",
            feature: "к скорости атаки",
        }],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "tome of knowledge",
        image: require("image/items/Tome_of_Knowledge_icon.png"),
        price: "150",
        add_stats: [],
        usage: "enlighten",
        description: "Дает 500 базового опыта +135 за каждое предыдущее применение этого предмета в вашей команде.",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "blade of alacrity",
        image: require("image/items/Blade_of_Alacrity_icon.png"),
        price: "1000",
        add_stats: [{
            value: "+10 ",
            feature: "к ловкости",
        }],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: true,
        title: "helm of iron will",
        image: require("image/items/Helm_of_Iron_Will_icon.png"),
        price: "900",
        add_stats: [
            {
                value: "+5 ",
                feature: "к броне,",
            },
            {
                value: "+3 ",
                feature: "к регенирации здоровья",
            },
        ],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "gem of true sight",
        image: require("image/items/Gem_of_True_Sight_icon.png"),
        price: "900",
        add_stats: [],
        usage: "true sight",
        description: "Дает владельцу и его союзникам возможность видеть невидимых существ и варды в радиусе 900. Предмет выпадает при смерте и не может быть уничтожен.",
        notation: "",
    },
    {
        base_shop: false,
        secretShop: true,
        sideShop: false,
        title: "ultimate orb",
        image: require("image/items/Ultimate_Orb_icon.png"),
        price: "2150",
        add_stats: [{
            value: "+10 ",
            feature: "ко всем атрибутам",
        }],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "dust of appearance",
        image: require("image/items/Dust_of_Appearance_icon.png"),
        price: "180",
        add_stats: [],
        usage: "reveal",
        description: "Делает всех невидимых героев в радиусе 1050 видимыми и замедляет их на 20%. Эффект длится 12 сек.",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "staff of wizardry",
        image: require("image/items/Staff_of_Wizardry_icon.png"),
        price: "1000",
        add_stats: [{
            value: "+10 ",
            feature: "к интеллекту",
        }],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "javelin",
        image: require("image/items/Javelin_icon.png"),
        price: "1100",
        add_stats: [],
        usage: "pierce",
        description: "Каждая атака может с вероятностью в 25% пройти сквозь уклонение и нанести 100 магического урона",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: true,
        title: "morbid mask",
        image: require("image/items/Morbid_Mask_icon.png"),
        price: "1100",
        add_stats: [{
            value: "+10 ",
            feature: "к урону",
        }],
        usage: "lifesteal",
        description: "Каждая атака восстанавливает владельцу здоровье в размере 15% от нанесенного урона.",
        notation: "",
    },
    {
        base_shop: false,
        secretShop: true,
        sideShop: false,
        title: "demon edge",
        image: require("image/items/Demon_Edge_icon.png"),
        price: "2200",
        add_stats: [{
            value: "+42 ",
            feature: "к урону",
        }],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "animal courier",
        image: require("image/items/Animal_Courier_(Radiant)_icon.png"),
        price: "50",
        add_stats: [],
        usage: "",
        description: "Создает существо, которое переносит вещи на базу и обратно",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: true,
        title: "broadsword",
        image: require("image/items/Broadsword_icon.png"),
        price: "1200",
        add_stats: [{
            value: "+18 ",
            feature: "к урону",
        }],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "shadow amulet",
        image: require("image/items/Shadow_Amulet_icon.png"),
        price: "1300",
        add_stats: [{
            value: "+20 ",
            feature: "к скорости атаки",
        }],
        usage: "fade",
        description: "Накладывает на героя или выбранного союзника невидимость, которая действует, пока цель стоит на месте. Цель входит в невидимость за 1.25 сек. и мгновенно мгновенно выходит из нее при передвижении. Не начинает перезаряжаться, если применить на себя.",
        notation: "Дальность применения: 600",
    },
    {
        base_shop: false,
        secretShop: true,
        sideShop: false,
        title: "mystic staff",
        image: require("image/items/Mystic_Staff_icon.png"),
        price: "2700",
        add_stats: [{
            value: "+25 ",
            feature: "к интеллекту",
        }],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "claymore",
        image: require("image/items/Claymore_icon.png"),
        price: "1400",
        add_stats: [{
            value: "+21 ",
            feature: "к урону",
        }],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "ghost scepeter",
        image: require("image/items/Ghost_Scepter_icon.png"),
        price: "1500",
        add_stats: [{
            value: "+5 ",
            feature: "ко всем атрибутам",
        }],
        usage: "ghost form",
        description: "Придает владельцу бесплотную форму, в которой он полностью защищен от физического урона, но не может атаковать и получает на 40% больше магического урона. Действует 4 сек.",
        notation: "",
    },
    {
        base_shop: false,
        secretShop: true,
        sideShop: false,
        title: "reaver",
        image: require("image/items/Reaver_icon.png"),
        price: "3000",
        add_stats: [{
            value: "+25 ",
            feature: "к силе",
        }],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: false,
        title: "mithril hammer",
        image: require("image/items/Mithril_Hammer_icon.png"),
        price: "1600",
        add_stats: [{
            value: "+24 ",
            feature: "к урону",
        }],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: true,
        secretShop: false,
        sideShop: true,
        title: "blink dagger",
        image: require("image/items/Blink_Dagger_icon.png"),
        price: "2250",
        add_stats: [],
        usage: "blink",
        description: "Телепортирует к указанной точке на расстоянии до 1200 единиц. предмет нельзя использовать, если последние 3 сек. его владелец получал урон от вражеских героев или Рошана.",
        notation: "",
    },
    {
        base_shop: false,
        secretShop: true,
        sideShop: false,
        title: "eaglesong",
        image: require("image/items/Eaglesong_icon.png"),
        price: "3200",
        add_stats: [{
            value: "+25 ",
            feature: "к ловкости",
        }],
        usage: "",
        description: "",
        notation: "",
    },
    {
        base_shop: false,
        secretShop: true,
        sideShop: false,
        title: "sacred relic",
        image: require("image/items/Sacred_Relic_icon.png"),
        price: "3800",
        add_stats: [{
            value: "+60 ",
            feature: "к урону",
        }],
        usage: "",
        description: "",
        notation: "",
    },
]